import {useEffect,useRef,useState} from 'react';
import {defaultInvite} from '../Invitation';
import type {InviteData} from '../Invitation';
import {newGuestKey,rememberGuest,guestKeys} from '../guest-api';
import StudioPreview,{studioSections} from './StudioPreview';
import FloatingCopilot from './FloatingCopilot';
import LoveRobot from './LoveRobot';
import schema from '../../public/studio/fields.json';
import './studio-page.css';
type Draft={id:string;template:string;data:InviteData;html:string;revision:number;gitSha?:string;busy:boolean;publishedSlug?:string};
type Credentials={id:string;token:string};
type Message={role:'user'|'assistant';text:string};
const storage='findmyinvite-studio-v1';
function savedKey():Credentials|null{try{const x=JSON.parse(localStorage.getItem(storage)||'null');return x&&typeof x.id==='string'&&typeof x.token==='string'?x:null}catch{return null}}
async function request<T>(action:string,credentials?:Credentials|null,body?:unknown,waitUntil=Date.now()+90000):Promise<T>{const r=await fetch('/api/studio?action='+action+(credentials?'&id='+credentials.id:''),{method:body===undefined?'GET':'POST',headers:{...(body===undefined?{}:{'Content-Type':'application/json'}),...(credentials?{Authorization:'Bearer '+credentials.token}:{})},body:body===undefined?undefined:JSON.stringify(body),cache:'no-store'});const raw=await r.text();let json;try{json=JSON.parse(raw)}catch{throw Error(/zscaler/i.test(raw)?'Your network security service (Zscaler) blocked this request. Ask your network administrator to permit FindMyInvite API requests.':'The server returned an unexpected page. Please reload and try again.')}if(r.status===423&&Date.now()<waitUntil){await new Promise(resolve=>setTimeout(resolve,1000));return request<T>(action,credentials,body,waitUntil);}if(!r.ok)throw Object.assign(Error(json.error||'Could not complete this step.'),{status:r.status});return json;}
export default function Studio(){
 const [credentials,setCredentials]=useState(savedKey),[draft,setDraft]=useState<Draft|null>(null),[section,setSection]=useState('hero'),[phone,setPhone]=useState(false),[busy,setBusy]=useState(false),[status,setStatus]=useState('Your ideas. A little love. Your invitation.'),[error,setError]=useState(''),[drawer,setDrawer]=useState<'details'|'publish'|'history'|null>(null),[messages,setMessages]=useState<Message[]>([{role:'assistant',text:'Hi, I’m Lovebot ♡ Let’s make this invitation yours. Tell me what you’d like to change, or skip ahead to the next section.'}]),[slug,setSlug]=useState(''),[versions,setVersions]=useState<{revision:number;message:string;created_at:string}[]>([]),[dirty,setDirty]=useState(false);
 const [editElapsed,setEditElapsed]=useState<number|null>(null);
 const editStarted=useRef<number|null>(null);
 const sending=useRef(false);
 const alive=useRef(true),polling=useRef(false),warming=useRef<Promise<unknown>|null>(null);
 const [workspaceLoading,setWorkspaceLoading]=useState(false);
 async function warm(key:Credentials){if(warming.current)return warming.current;setWorkspaceLoading(true);setStatus('Preparing your editing workspace...');const task=(async()=>{for(let n=0;n<30&&alive.current;n++){const state=await request<{ready:boolean}>('prepare',key,{});if(state.ready){setStatus('Workspace ready');return;}await new Promise(r=>setTimeout(r,1500));}setStatus('Workspace will reconnect on your next edit');})().catch(()=>{if(alive.current)setStatus('Your draft is safe; workspace reconnects on your next edit')}).finally(()=>{warming.current=null;if(alive.current)setWorkspaceLoading(false)});warming.current=task;return task;}
 useEffect(()=>{const close=(e:KeyboardEvent)=>{if(e.key==='Escape')setDrawer(null)};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[]);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false}},[]);
 useEffect(()=>{if(!credentials)return;request<Draft>('read',credentials).then(d=>{setDraft(d);setSlug(d.publishedSlug||'');if(d.busy)void poll(credentials);else void warm(credentials)}).catch(e=>setError(e.message))},[credentials?.id]);
 useEffect(()=>{const protect=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',protect);return()=>window.removeEventListener('beforeunload',protect)},[dirty]);
 async function poll(key:Credentials){if(polling.current)return;polling.current=true;setBusy(true);try{for(let deadline=Date.now()+300000;Date.now()<deadline&&alive.current;){let d:Draft&{done:boolean;message?:string;status?:string};try{d=await request('poll',key,{});}catch(e){if((e as Error&{status?:number}).status===409){await new Promise(r=>setTimeout(r,750));continue;}throw e;}if(!alive.current)return;if(d.done){if(editStarted.current!==null){setEditElapsed((performance.now()-editStarted.current)/1000);editStarted.current=null;}setDraft(d);setStatus('Your preview is up to date');if(d.message)setMessages(m=>[...m,{role:'assistant',text:d.message!}]);setDirty(false);return;}setStatus(d.status||'Customizing your invitation…');await new Promise(r=>setTimeout(r,750));}if(alive.current)setError('This is taking longer than expected. Reload to reconnect to the saved task.');}catch(e){if(alive.current){setError((e as Error).message);setMessages(m=>[...m,{role:'assistant',text:(e as Error).message}]);if(key)request<Draft>('read',key).then(setDraft).catch(()=>{});}}finally{polling.current=false;if(alive.current)setBusy(false)}}
 async function create(template:string){setBusy(true);setError('');try{const token=newGuestKey('draft').token;const data={...structuredClone(defaultInvite),template,groom:template==='royal-temple'?'Rohan':'Aryan',bride:template==='royal-temple'?'Ananya':'Eva',date:new Date(Date.now()+45*86400000).toISOString().slice(0,10),music:template==='royal-temple'?'/assets/temple/invite-bg.mp3':'/assets/track1.mp3'};data.timeline=data.timeline.map(e=>({...e,time:data.date+'T'+(e.time.split('T')[1]||'10:00')}));data.preEvents=[];data.welcome='With our families, we invite you to celebrate our wedding.';data.groomDetails='With his loving family';data.brideDetails='With her loving family';const d=await request<Draft>('create',null,{template,token,data});const key={id:d.id,token};localStorage.setItem(storage,JSON.stringify(key));setCredentials(key);setDraft(d);}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function save(){if(!draft||!credentials)return null;await warming.current;const d=await request<Draft>('save',credentials,{data:draft.data,revision:draft.revision});setDraft(d);setDirty(false);return d;}
 async function send(message:string){if(!draft||!credentials||sending.current)return;sending.current=true;editStarted.current=performance.now();setBusy(true);setError('');setMessages(m=>[...m,{role:'user',text:message}]);try{await warming.current;setStatus('Lovebot is editing your invitation…');const current=dirty?await save():draft;await request('run',credentials,{message,section,revision:current!.revision});setStatus('Lovebot is editing your invitation…');setBusy(false);await poll(credentials);}catch(e){setError((e as Error).message);setMessages(m=>[...m,{role:'assistant',text:(e as Error).message}]);setBusy(false)}finally{sending.current=false}}
 function changeData(key:string,value:unknown){setDraft(d=>d?{...d,data:{...d.data,[key]:value}}:d);setDirty(true)}
 async function restore(target:number){if(!draft||!credentials)return;setBusy(true);setError('');try{const d=await request<Draft>('restore',credentials,{target,revision:draft.revision});setDraft(d);setDirty(false);setDrawer(null);setStatus('Previous version restored');}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function history(){if(!credentials)return;setError('');try{const x=await request<{versions:typeof versions}>('history',credentials);setVersions(x.versions);setDrawer('history')}catch(e){setError((e as Error).message)}}
 async function publish(e:React.FormEvent){e.preventDefault();if(!draft||!credentials)return;setBusy(true);setError('');try{const current=dirty?await save():draft;const key=guestKeys().find(k=>k.slug===slug)||newGuestKey(slug);rememberGuest(key);const next=await request<Draft>('publish',credentials,{slug,managementToken:key.token,revision:current!.revision});setDraft(next);setStatus('Your invitation is published');}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 if(!draft)return <main className="studio-access"><div className="studio-access-card"><LoveRobot/><p style={{letterSpacing:3,fontSize:10}}>YOUR NEXT BEAUTIFUL BEGINNING</p><h1>Choose your canvas.</h1><p>Start with a design you love.<br/>We’ll make every detail feel like you.</p><label className="studio-help">Restore a private draft<input type="file" accept="application/json,.json" onChange={async e=>{try{const f=e.target.files?.[0];if(!f)return;const key=JSON.parse(await f.text());if(!/^[a-f0-9-]{36}$/.test(key.id)||!/^[a-f0-9]{64}$/.test(key.token))throw Error('Choose a valid studio recovery file.');const d=await request<Draft>('read',key);localStorage.setItem(storage,JSON.stringify(key));setCredentials(key);setDraft(d);setSlug(d.publishedSlug||'')}catch(err){setError((err as Error).message)}}}/></label><div className="studio-template-options">{Object.entries(schema.templates).map(([id,t])=><button className="studio-template-option" key={id} disabled={busy} onClick={()=>create(id)}><span className="studio-swatch" style={{background:id==='royal-temple'?'linear-gradient(#d8e9ec,#e8d4ac)':'linear-gradient(130deg,#072b22,#18583e)',border:'1px solid #cdb57f'}}/><span><b>{t.name}</b><small>{id==='royal-temple'?'A celebration written in the clouds':'An elegant beginning in emerald & gold'}</small></span></button>)}</div>{busy&&<p role="status">Preparing your private invitation…</p>}{error&&<p className="studio-error" role="alert">{error}</p>}{credentials&&<button className="studio-reset" onClick={()=>{localStorage.removeItem(storage);setCredentials(null);setError('')}}>Start a new draft</button>}</div></main>;
 return <main className="studio-page"><header className="studio-bar"><a href="/studio" className="studio-brand">FindMyInvite<span>♡</span><small>THE LOVE STUDIO</small></a><div className={'studio-progress'+(busy?' busy':'')} role="status"><i/>{busy||workspaceLoading?status:dirty?'Unsaved preview changes':editElapsed===null?'Private draft · saved':`Saved in ${editElapsed.toFixed(1)}s`}</div><div className="studio-toolbar"><button className="desktop-only" onClick={()=>setPhone(!phone)}>{phone?'Desktop view':'Mobile view'}</button><button onClick={()=>setDrawer('details')} disabled={busy}>Details</button><button className="desktop-only" onClick={history} disabled={busy}>History</button><button className="primary" onClick={()=>setDrawer('publish')} disabled={busy}>Publish ↗</button></div></header>
 <select aria-label="Invitation section" className="studio-mobile-sections" value={section} onChange={e=>setSection(e.target.value)}>{studioSections.map((s,i)=><option value={s.id} key={s.id}>{i+1} / {studioSections.length} · {s.label}</option>)}</select>
 <div className="studio-workspace"><aside className="studio-sidebar"><h2>Your story, in chapters</h2>{studioSections.map((s,i)=><button key={s.id} className={'studio-section'+(section===s.id?' active':'')} onClick={()=>setSection(s.id)}><b>{i+1}</b>{s.label}</button>)}<p className="studio-note">Tell Lovebot what feels right.<br/>Watch your invitation become yours, one little detail at a time.</p><p className="studio-version">VERSION {draft.revision+1} · {schema.templates[draft.template as keyof typeof schema.templates]?.name}</p><button className="studio-reset" onClick={()=>{if(dirty&&!confirm('Leave unsaved preview changes?'))return;const links=JSON.parse(localStorage.getItem('findmyinvite-studio-history')||'[]');localStorage.setItem('findmyinvite-studio-history',JSON.stringify([...links,credentials]));localStorage.removeItem(storage);setCredentials(null);setDraft(null);setDirty(false);}}>Create another invitation</button><button className="studio-reset" onClick={()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(credentials)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='fmi-private-studio-recovery.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}}>Save private draft access</button></aside><div className="studio-canvas"><StudioPreview html={draft.html} data={draft.data} section={section} onSection={setSection} phone={phone}/></div></div>
 <FloatingCopilot sections={studioSections} activeSection={section} onSection={setSection} onSend={send} busy={busy} messages={messages} status={status} onUndo={()=>void restore(Math.max(0,draft.revision-1))} canUndo={draft.revision>0&&!busy&&!dirty}/>
 {busy&&<button className="studio-button" style={{position:'fixed',bottom:8,left:8,zIndex:60,fontSize:10}} onClick={async()=>{if(credentials){try{const d=await request<Draft>('cancel',credentials,{});setDraft(d);setStatus('Change cancelled.')}catch(e){setError((e as Error).message)}}}}>Cancel current change</button>}
 {error&&!drawer&&<div className="studio-error" role="alert" style={{position:'fixed',top:80,left:'50%',transform:'translateX(-50%)',zIndex:90,maxWidth:'90vw'}} onClick={()=>setError('')}>{error} · Dismiss</div>}
 {drawer&&<div className="studio-drawer-backdrop" onClick={()=>setDrawer(null)}><section className="studio-drawer" role="dialog" aria-modal="true" aria-label={drawer==='details'?'Review invitation details':drawer==='publish'?'Publish invitation':'Version history'} onClick={e=>e.stopPropagation()}><header><h2>{drawer==='details'?'Every little detail.':drawer==='publish'?'Ready to share?':'Your creative journey.'}</h2><button className="studio-button" onClick={()=>setDrawer(null)} aria-label="Close panel">✕</button></header>{error&&<p className="studio-error" role="alert">{error}</p>}
 {drawer==='details'&&<form className="studio-fields" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await save();setStatus('Details saved');setDrawer(null)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><p className="studio-help">Changes appear in your private preview immediately. Save when you’re happy; publish when you’re ready for guests.</p>{schema.fields.map(f=><label key={f.key}>{f.label}{f.required?' *':''}{f.type==='textarea'?<textarea maxLength={f.max} value={String(draft.data[f.key as keyof InviteData]||'')} onFocus={()=>setSection(f.section)} onChange={e=>changeData(f.key,e.target.value)}/>:<input type={f.type} maxLength={f.max} value={String(draft.data[f.key as keyof InviteData]||'')} onFocus={()=>setSection(f.section)} onChange={e=>changeData(f.key,e.target.value)}/>}</label>)}
 {(['timeline','preEvents'] as const).map(key=><div key={key}><h3>{key==='timeline'?'Your celebrations':'Pre-wedding events'}</h3>{draft.data[key].map((e,i)=><div className="studio-event-editor" key={i}>{(['title','time','description'] as const).map(field=><label key={field}>{field}<input type={field==='time'?'datetime-local':'text'} value={e[field]} onChange={ev=>changeData(key,draft.data[key].map((x,n)=>n===i?{...x,[field]:ev.target.value}:x))}/></label>)}<button type="button" className="studio-button" onClick={()=>changeData(key,draft.data[key].filter((_,n)=>n!==i))}>Remove event</button></div>)}<button className="studio-button" type="button" onClick={()=>changeData(key,[...draft.data[key],{title:'',time:'',description:''}])}>+ Add event</button></div>)}
 <h3 style={{marginTop:25}}>Your photos</h3><p className="studio-help">This team pilot uses the existing photo library. Personal photo uploads are a follow-up.</p>{draft.data.photos.map((photo,i)=><label key={i}>Photo {i+1}<select value={photo} onChange={e=>changeData('photos',draft.data.photos.map((p,n)=>n===i?e.target.value:p))}>{Array.from(new Set([...defaultInvite.photos,...draft.data.photos])).map((p,n)=><option value={p} key={p}>Library photo {n+1}</option>)}</select></label>)}<h3 style={{marginTop:25}}>Visible sections</h3>{studioSections.filter(s=>s.id!=='hero').map(s=><label className="studio-checkbox" key={s.id}><input type="checkbox" checked={draft.data.sections[s.id]!==false} onChange={e=>changeData('sections',{...draft.data.sections,[s.id]:e.target.checked})}/>{s.label}</label>)}<label>Background music<select value={draft.data.music} onChange={e=>changeData('music',e.target.value)}><option value="">No music</option><option value="/assets/track1.mp3">Gentle celebration</option><option value="/assets/track3.mp3">Royal celebration</option>{draft.template==='royal-temple'&&<option value="/assets/temple/invite-bg.mp3">Temple original</option>}</select></label><div className="studio-save-row"><button className="studio-button primary" disabled={busy}>{busy?'Saving…':'Save my details'}</button><button type="button" className="studio-button" onClick={history}>Version history</button><button type="button" className="studio-button" onClick={()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(credentials)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='fmi-private-studio-recovery.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}}>Save access</button></div></form>}
 {drawer==='history'&&<><p className="studio-help">Restore a saved version to your draft. Your published invitation stays unchanged.</p>{versions.map(v=><button className="studio-history-row" key={v.revision} disabled={busy||v.revision===draft.revision} onClick={()=>restore(v.revision)}><b>Version {v.revision+1}{v.revision===draft.revision?' · Current':''}</b><p>{v.message}</p><small>{new Date(v.created_at).toLocaleString()}</small></button>)}</>}
 {drawer==='publish'&&<form className="studio-fields" onSubmit={publish}><p className="studio-help">Publish this exact version for your guests. Future edits stay private until you publish again.</p><label>Your invitation address<input required pattern="[a-z0-9][a-z0-9-]{1,46}[a-z0-9]" placeholder="ashok-and-supriya" value={slug} readOnly={Boolean(draft.publishedSlug)} onChange={e=>setSlug(e.target.value.toLowerCase().replace(/[^a-z0-9-]/g,''))}/><small>{location.origin}/{slug||'your-story'}</small></label><button className="studio-button primary" disabled={busy}>{busy?'Publishing…':draft.publishedSlug?'Publish these changes':'Publish my invitation'}</button>{draft.publishedSlug&&<div className="studio-success"><p>Your invitation is live.</p><a href={'/'+draft.publishedSlug} target="_blank" rel="noreferrer">Open guest invitation ↗</a><p><a href={'/manage/'+draft.publishedSlug}>Guest responses & recovery link</a></p></div>}</form>}
 </section></div>}
 </main>;
}
