import renderers from '../../public/studio/renderers.json';
import {useEffect,useMemo,useRef,useState} from 'react';
import Invitation from '../Invitation';
import type {InviteData} from '../Invitation';
import {api} from '../guest-api';
export const studioSections=[{id:'hero',label:'The opening'},{id:'welcome',label:'Your invitation'},{id:'timeline',label:'The celebrations'},{id:'gallery',label:'Your moments'},{id:'venue',label:'The venue'},{id:'rsvp',label:'Guest responses'}];
function bridge(channel:string){return `(()=>{const channel=${JSON.stringify(channel)};let data={};let editing=false;const send=(type,payload={})=>parent.postMessage({channel,type,...payload},'*');const field=(key)=>data[key]||'';
const staticText=[...document.querySelectorAll('[data-editor-text],[data-section] p,[data-section] h1,[data-section] h2,[data-section] h3,[data-section] span,[data-section] label')].filter(el=>!el.children.length&&el.textContent.trim()&&!el.closest('[data-field],[data-events],[data-no-edit],button,a,svg,form')&&(el.hasAttribute('data-editor-text')||!el.closest('[id*=countdown],[class*=countdown]')));
staticText.forEach((el,i)=>{el.dataset.editorText=el.dataset.editorText||'text-'+i;el.dataset.originalText=el.textContent;});
function mark(){document.querySelectorAll('[data-editor-text],[data-field],[data-edit-event]').forEach(el=>{if(!el.closest('form')){el.classList.toggle('fmi-editable',editing);if(editing){el.setAttribute('tabindex','0');el.setAttribute('role','button');el.setAttribute('aria-label','Edit '+(el.dataset.field||el.textContent.trim().slice(0,60)));}else{el.removeAttribute('tabindex');el.removeAttribute('role');el.removeAttribute('aria-label');}}});}
document.addEventListener('click',e=>{if(!editing)return;const el=e.target.closest('[data-field],[data-editor-text],[data-edit-event]');if(!el||el.closest('form'))return;e.preventDefault();e.stopImmediatePropagation();document.querySelectorAll('.fmi-selected').forEach(n=>n.classList.remove('fmi-selected'));el.classList.add('fmi-selected');send('edit-text',{key:el.dataset.field?'field:'+el.dataset.field:el.dataset.editEvent?'event:'+el.dataset.editEvent:el.dataset.editorText,value:el.textContent,section:el.closest('[data-section]')?.dataset.section});},true);
document.addEventListener('keydown',e=>{if(editing&&(e.key==='Enter'||e.key===' ')&&e.target.classList.contains('fmi-editable')){e.preventDefault();e.target.click();}});
function update(d){staticText.forEach(el=>{el.textContent=d.textOverrides?.[el.dataset.editorText]??el.dataset.originalText;});data=d;window.fmiData=d;document.querySelectorAll('[data-field]').forEach(el=>{let value=d[el.dataset.field]||'';if(el.dataset.field==='date'&&value){const date=new Date(value+'T12:00:00');if(!isNaN(+date))value=date.toLocaleDateString('en-IN',{day:'numeric',month:'long',year:'numeric'});}el.textContent=value;});document.querySelectorAll('[data-photo]').forEach(el=>{const src=d.photos?.[Number(el.dataset.photo)];if(src){el.src=src;el.hidden=false}else el.hidden=true;});document.querySelectorAll('[data-events]').forEach(el=>{el.replaceChildren();(d[el.dataset.events]||[]).forEach((e,index)=>{const card=document.createElement('article');card.className='fmi-event-card';const title=document.createElement('h3'),time=document.createElement('p'),text=document.createElement('p');title.dataset.editEvent=el.dataset.events+'.'+index+'.title';time.dataset.editEvent=el.dataset.events+'.'+index+'.time';text.dataset.editEvent=el.dataset.events+'.'+index+'.description';title.textContent=e.title;const date=new Date(e.time);time.textContent=isNaN(+date)?'Time to be confirmed':date.toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'});text.textContent=e.description;card.append(title,time,text);el.append(card);});});for(const id of ['welcome','timeline','gallery','venue','rsvp']){const el=document.querySelector('[data-section="'+id+'"]');if(el)el.hidden=d.sections?.[id]===false;}document.dispatchEvent(new CustomEvent('fmi:updated',{detail:d}));mark();}
addEventListener('message',e=>{if(e.source!==parent||e.data?.channel!==channel)return;if(e.data.type==='editing'){editing=Boolean(e.data.enabled);mark();}if(e.data.type==='update')update(e.data.data);if(e.data.type==='section'){const el=document.querySelector('[data-section="'+e.data.section+'"]');if(el){document.body.style.overflow='auto';el.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});}}if(e.data.type==='rsvp-result'){const el=document.getElementById('fmi-rsvp-status');if(el)el.textContent=e.data.message;const btn=document.querySelector('#fmi-rsvp button[type=submit]');if(btn)btn.disabled=false;}});
const email=document.querySelector('#fmi-rsvp input[name=email]');if(email)email.required=true;
document.addEventListener('submit',e=>{if(e.target.id!=='fmi-rsvp')return;e.preventDefault();e.stopImmediatePropagation();const f=e.target;let status=document.getElementById('fmi-rsvp-status');if(!status){status=document.createElement('p');status.id='fmi-rsvp-status';status.setAttribute('role','status');f.append(status);}status.textContent='Sending your response…';const btn=f.querySelector('button[type=submit]');if(btn)btn.disabled=true;send('rsvp',{fields:Object.fromEntries(new FormData(f))});},true);
let timer;addEventListener('scroll',()=>{clearTimeout(timer);timer=setTimeout(()=>{let active;document.querySelectorAll('[data-section]').forEach(el=>{if(!el.hidden&&el.getBoundingClientRect().top<innerHeight*.5)active=el.dataset.section;});if(active)send('section',{section:active});},100)},{passive:true});
document.addEventListener('click',e=>{const a=e.target.closest('a');if(a?.hasAttribute('download')&&a.href.startsWith('blob:'))return;if(a&&a.href&&!a.getAttribute('href').startsWith('#')){e.preventDefault();send('link',{url:a.href});}});
send('ready');})();`}
export function previewDocument(html:string,channel:string){
 const doc=new DOMParser().parseFromString(html,'text/html');doc.querySelectorAll('meta[http-equiv],base').forEach(n=>n.remove());
 const csp=doc.createElement('meta');csp.httpEquiv='Content-Security-Policy';csp.content=`default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline' ${location.origin}; img-src ${location.origin} data: blob:; font-src ${location.origin}; media-src ${location.origin}; connect-src 'none'; form-action 'none'; base-uri 'none';`;doc.head.prepend(csp);
 const style=doc.createElement('style');style.textContent='[hidden]{display:none!important}html{scroll-behavior:smooth}body{margin:0;overflow-x:hidden}[data-section]{scroll-margin-top:16px}.fmi-editable{pointer-events:auto!important;cursor:text!important;outline:1px dashed #bda06488;outline-offset:5px;border-radius:3px;min-height:1em}.fmi-editable:focus,.fmi-editable:hover,.fmi-selected{outline:2px solid #bb8d36!important;outline-offset:5px}.fmi-event-card{padding:20px 14px;text-align:center}.fmi-event-card h3{font-family:inherit;font-size:1.7rem;margin:0 0 10px}.fmi-event-card p{margin:8px 0;line-height:1.6}';doc.head.append(style);
 const script=doc.createElement('script');script.textContent=bridge(channel);doc.body.append(script);return '<!doctype html>'+doc.documentElement.outerHTML;
}
export default function StudioPreview({html,data,section,onSection,onRsvp,onEdit,editable=false,phone=false}:{html:string;data:InviteData;section?:string;onSection?:(id:string)=>void;onRsvp?:(fields:Record<string,FormDataEntryValue>)=>Promise<void>;phone?:boolean;editable?:boolean;onEdit?:(selection:{key:string;value:string;section?:string})=>void}){
 const iframe=useRef<HTMLIFrameElement>(null),[channel]=useState(()=>crypto.randomUUID());const document=useMemo(()=>previewDocument(html,channel),[html,channel]);
 const dataRef=useRef(data);dataRef.current=data;const observedSection=useRef<string|undefined>(undefined);
 const send=(type:string,payload:object={})=>iframe.current?.contentWindow?.postMessage({channel,type,...payload},'*');
 useEffect(()=>{send('editing',{enabled:editable})},[editable,document]);
 useEffect(()=>{send('update',{data})},[data,document]);useEffect(()=>{if(section&&section!==observedSection.current)send('section',{section});observedSection.current=undefined;},[section,document]);
 useEffect(()=>{const receive=async(e:MessageEvent)=>{if(e.source!==iframe.current?.contentWindow||e.data?.channel!==channel)return;
 if(e.data.type==='edit-text'&&editable&&typeof e.data.key==='string'&&typeof e.data.value==='string')onEdit?.({key:e.data.key,value:e.data.value,section:e.data.section});
 if(e.data.type==='ready'){send('editing',{enabled:editable});send('update',{data:dataRef.current});if(section)send('section',{section});}
 if(e.data.type==='section'&&studioSections.some(s=>s.id===e.data.section)){observedSection.current=e.data.section;onSection?.(e.data.section);}
 if(e.data.type==='rsvp'){try{if(onRsvp){await onRsvp(e.data.fields);send('rsvp-result',{message:'Thank you! Your response has been sent to the host.'});}else send('rsvp-result',{message:'Preview only — publish your invitation to collect guest responses.'});}catch(error){send('rsvp-result',{message:(error as Error).message});}}
 if(e.data.type==='link'){try{const u=new URL(e.data.url);if(u.protocol==='https:'&&['www.google.com','maps.google.com','calendar.google.com'].includes(u.hostname))window.open(u.href,'_blank','noopener,noreferrer');}catch{/* Ignore malformed template links. */}}
 };window.addEventListener('message',receive);return()=>window.removeEventListener('message',receive)},[channel,onSection,onRsvp,section,editable,onEdit]);
 return <iframe ref={iframe} title="Your invitation live preview" style={{width:'100%',height:'100%',display:'block',border:0}} className={'studio-preview-frame'+(phone?' is-phone':'')} sandbox="allow-scripts allow-downloads allow-forms" srcDoc={document}/>;
}
export function PublishedStudio({slug}:{slug:string}){const [page,setPage]=useState<{html:string;data:InviteData}|null>(null),[error,setError]=useState('');useEffect(()=>{fetch('/api/studio?action=public&slug='+encodeURIComponent(slug)).then(async r=>{const j=await r.json();if(!r.ok)throw Error(j.error);return j}).then(setPage).catch(e=>setError(e.message))},[slug]);if(error)return <main className="editor-shell"><h1>Invitation unavailable</h1><p>{error}</p></main>;if(!page)return <p>Opening your invitation…</p>;if(!renderers.htmlTemplates.includes(page.data.template))return <Invitation cloudData={page.data} onRsvp={async fields=>{await api('rsvp',slug,'',fields)}}/>;return <div style={{height:'100dvh'}}><StudioPreview html={page.html} data={page.data} onRsvp={async fields=>{await api('rsvp',slug,'',fields)}}/></div>}
