#!/usr/bin/env python3
"""christian-v2 'christian_remix': OG Christian church wedding template v1 (kerala-christian-vtv-mood/template.json, 'The Wedding of Alex & Anna')
scene order + ALL OG text verbatim, OG art style + OG floating typography, remixed with Maniraj's Noctilux angles and props.
Main church described from reference/insp-14-church-backwater.jpg in TEXT only (never sent). Different couple/outfits, no Hindu elements."""
import json
from pathlib import Path
R = Path(__file__).resolve().parents[2]; OUT = R/"scripts/christian-v2"
OG = json.load(open("/workspace/fmi-productions/kerala-christian-vtv-mood/template.json")); P = OG["parameters"]
L = lambda k: P[k].split("\n")
g4 = (R/"scripts/still_groom_v4_prompt.txt").read_text()
lens = g4[g4.index("CAMERA AND LENS"):g4.index("FLOWERS (abundant)")].strip()
for a, b in [("placed exactly on the Tamil lettering and the hero subject at that same depth", "placed exactly on the gold lettering and the hero subject at that same depth"),
             ("(lamp flames, fairy lights, hanging-lamp glints, brass highlights)", "(candle flames, lantern glows, fairy lights, gold highlights)")]:
    assert lens.count(a) == 1; lens = lens.replace(a, b)
og_style = OG["style"]
for a, b in [("Cream-white Portuguese-influenced plaster walls, laterite stone accents, arched windows, a modest bell tower and a simple cross.",
              "ONE white Kerala Gothic church beside a calm backwater (see CHURCH below)."),
             ("Floor is subtly reflective worn cream stone or polished laterite tile, not a mirror.", "Floors are subtly reflective worn white stone or polished tile, not a mirror."),
             ("Fixed floral church wedding décor of white jasmine, soft pink roses, baby's breath and green foliage — not marigold temple swags as primary.",
              "Fixed Christian wedding décor of white and blush-pink roses, white lilies, baby's breath, eucalyptus and soft greenery, ivory satin ribbons, pew bows, glass lanterns and tall white candles."),
             ("Generate only from this text, no reference image. No watermark, interface, duplicate people, extra signs or unintended words.", "")]:
    assert og_style.count(a) == 1, a; og_style = og_style.replace(a, b)
CHURCH = ("CHURCH (the one main church, exterior and matching interiors): a white Kerala Gothic church facade beside a backwater, with a central pointed gable topped by a gold cross, a round blue medallion with a green laurel wreath set in the gable, "
          "tall pointed lancet windows with grey trim, slender white pinnacle turrets each topped by a small cross, and grey-outlined geometric chevron details; it stands behind a white balustrade fence along the water's edge, "
          "with terracotta-tiled roofs beside it and a red-roofed building nearby, coconut palms, soft sky and rippling water reflections. Its interior matches: white pointed Gothic arches, lancet stained-glass windows in soft blue, rose and gold, polished dark wooden pews, a simple altar with a plain cross.")
STYLE = (og_style.strip() + " " + CHURCH + " " + lens +
         " CHRISTIAN STYLING ONLY: no Hindu elements of any kind — no bindi or forehead marks, no henna, no temple jewellery, no marigolds, no lotus, no jasmine strings, no brass oil lamps, no kolam or Hindu motifs."
         " Generate only from this text, no reference image. No watermark, interface, duplicate people, extra signs or unintended words.")
T_TITLE = ("Exquisite ornate display lettering with graceful curved serifs, a gently arched first line, elegant varied stroke widths and modest flourishes. "
           "These are freestanding dimensional letters suspended in the open air, with luminous champagne-gold faces, antique-gold beveled edges, subtle warm halos and tiny bright edge glints. "
           "Rich gold, not brown engraving. No rectangular nameplate, printed wall text or letters attached to plaster. Readable counters and gaps between words, full title inside the frame.")
T_RULE = "Glowing lettering is solid beveled metal with light on its surface: no liquid gold, dripping strokes, ceiling-to-floor beams, explosive firework bursts or smoke emitted by text."
NOBOARD = "NO card, board, plaque, sign, easel or frame anywhere: every line floats freely in the air."
def LET(lines, extra=""):
    q = "\n".join(f"{i+1}) exactly '{t}'" for i, t in enumerate(lines))
    return ("LETTERING (floating, OG typography): " + T_TITLE + " " + T_RULE + " " + NOBOARD + (" " + extra if extra else "") +
            f" Exactly {len(lines)} lines, in this order, each exactly once, spelled exactly character for character, and no other words, letters or numbers anywhere:\n" + q)
NOTEXT = "NO TEXT: absolutely no lettering, words, numbers, logos, boards or signs anywhere in this image."
PEOPLE = ("CHARACTERS: premium animated adult characters with sculpted expressive faces in the same dimensional storybook-animation style, never photographic people; "
          "TALL adult proportions about 7.5 heads tall with long legs, never chibi or child-like; correct anatomy, five fingers on each hand.")
GROOM = ("The GROOM (identical wherever he appears): warm deep-brown skin, a strong friendly face, short textured black hair with a neat modern taper, a FULL, neatly groomed short black beard and moustache, warm confident smile. "
         "He wears a tailored deep plum / aubergine three-piece suit with a subtle tonal self-pattern, an ivory shirt and a champagne-gold silk tie, a white-and-blush rose boutonniere with a sprig of eucalyptus on the left lapel, "
         "polished dark-brown shoes and a stylish gold luxury chronograph watch on his wrist (plain dial with no numbers, words or logos).")
BRIDE = ("The BRIDE (identical wherever she appears): warm golden-brown skin, a heart-shaped face with large expressive eyes and a bright soft smile, long dark hair in soft side-swept waves, half-up, with a delicate pearl-and-blush-flower hair vine. "
         "She wears a pure WHITE off-the-shoulder ball gown with a sweetheart neckline and structured corset bodice, delicate 3D floral appliqué lace cascading from the bodice down a voluminous layered white tulle skirt, a long train, "
         "and a long cathedral veil with a scalloped lace edge. Accessories in blush and rose-gold: rose-gold pearl drop earrings, a delicate rose-gold cross pendant and a slim rose-gold bracelet. "
         "Her bouquet: white and blush-pink garden roses, white lilies, baby's breath and trailing eucalyptus, tied with a blush satin ribbon.")

S = {}
def add(sid, og, title, text, people, comp, lettering=None):
    S[sid] = dict(og_scene=og, title=title, text=text, people=people,
                  prompt=STYLE + "\n\n" + ((PEOPLE + "\n\n") if people else "") + (lettering if lettering is not None else (LET(text) if text else NOTEXT)) + "\n\nSCENE COMPOSITION:\n" + comp)

add("s01-aerial", "scene-01", "Aerial establish — drone over the backwater church", [], False,
"No people except a few tiny distant figures with no detail. A high oblique DRONE establishing shot from OVER THE WATER, the camera about 40 metres above the backwater and well back, looking diagonally down at about 20-25 degrees at the white Kerala Gothic church on the far bank: its pointed gable with the gold cross and the blue laurel medallion, lancet windows, pinnacle turrets, the white balustrade along the water's edge, terracotta roofs and the red-roofed building beside it, coconut palms around. A small wooden boat jetty decorated with white and blush rose swags and ivory ribbons reaches into the water in the lower foreground, a decorated wooden country boat with white flowers moored beside it; floating white flower bowls and candles drift on the water. Soft sunrise with a lavender-peach and powder-blue sky and gentle mist over the backwater, long soft reflections rippling in the water. Lavish white-and-blush wedding decoration on the balustrade, steps and turrets stays small in the landscape. No text.")
add("s02-blessing", "scene-02", "Blessing — glowing candle-lantern cross on the waterfront balustrade at dusk, 'With God's Grace / We Invite You' floating above", [P["devotional_line_1"], P["devotional_line_2"]], False,
"No people. Blue-hour dusk on the waterfront terrace in front of the backwater church. A creative LOW angle almost at stone level, looking slightly up along the white balustrade: on the broad white stone terrace in front of the balustrade, a large elegant CROSS is formed entirely by glowing white pillar candles in clear glass lanterns set in a precise cross shape on the stones (NOT flowers, no floral cross), their flames blooming into creamy golden orbs, the cross shape crisp and clearly readable. Behind it the white balustrade, the calm backwater reflecting the candle glow and the deep blue sky, and the softly lit white Gothic church facade with its gold gable cross across the water in creamy bokeh. Above the candle cross, in the upper-middle quarter, a LARGE two-line floating blessing title, spanning about 65-70 percent of frame width, separated clearly from the cross, in the razor-sharp focus plane with the candle cross. The warm candlelight and a last soft glow in the sky strike the letters. A few white and blush rose petals float at three depths, clear of the lettering and the cross.",
lettering=LET([P["devotional_line_1"], P["devotional_line_2"]]))
inv = L("invitation_lines")
add("s03-invitation", "scene-03", "Invitation — 'The Wedding of / Alex & Anna' floating at the church doorway", inv, False,
"No people. A creative HIGH three-quarter angle from the top of the church steps looking across the open carved wooden double doors of the white Gothic church: the pointed lancet doorway with grey trim, the doors swung open to the candlelit nave, the white steps lined with tall white candles in glass lanterns and white-and-blush rose arrangements with eucalyptus, ivory satin ribbons on the door handles, petals on the steps. Floating in the open air in front of the doorway, large and centred, in the razor-sharp focus plane. The first line is graceful expressive calligraphy, the lower line elegant wedding display lettering, all fully within generous margins. Warm morning sunbeams slant from the upper left across the doorway through haze. Floating white and blush petals at every depth, clear of the lettering.",
lettering=LET(inv, "The first line is graceful expressive calligraphy, the lower line elegant wedding display lettering."))
add("s04-groom", "scene-04", "Groom — on the waterfront balustrade, 'Mr. / Alex John' floating", [P["groom_title"], P["groom_name"]], True,
"Only ONE person, the groom. A creative LOW three-quarter angle from the front-LEFT at chest height, looking slightly up, on the white balustrade terrace by the backwater in soft morning light: the groom leans relaxed with one hand on the white balustrade and the other in his trouser pocket, his watch visible, turned slightly toward the right and smiling toward the camera, seen from about the knees up, in the LEFT half of the frame. " + GROOM +
" Behind him, the rippling backwater and the white Gothic church facade with its pinnacle turrets melt into creamy bokeh; white-and-blush rose swags with ivory ribbons on the balustrade. Floating on the RIGHT at chest height, at the same depth as his face and razor-sharp, spectacular fine champagne-gold calligraphy: a small first line and a graceful large line below. The gold letters have bright rim-lit beveled edges, gentle warm halos and a few tiny star-like glints along the flourishes, not a signboard. Floating white and blush petals at every depth, clear of his face and the lettering.")
add("s05-bride", "scene-05", "Bride — by a stained-glass lancet window in the nave, 'Ms. / Anna Thomas' floating", [P["bride_title"], P["bride_name"]], True,
"Only ONE person, the bride. A creative LOW three-quarter angle from the front-RIGHT at chest height, looking slightly up, inside the white Gothic nave beside a tall pointed lancet stained-glass window: the bride stands turned three-quarter toward the left, holding her bouquet at her waist with both hands, glancing over her bare shoulder toward the camera with a soft smile, seen from about the knees up, in the RIGHT half of the frame, her cathedral veil flowing behind her. " + BRIDE +
" Coloured light from the stained glass falls softly across the white tulle; behind her white pointed arches, pew-end bows and tall candles melt into creamy bokeh. On the LEFT, at chest height, at the same depth as her face and razor-sharp, floats a large exquisite luminous gold calligraphic title, small type above a large name in flowing thin strokes. Bright golden bevels and soft warm halo, sharp readable letters. Floating white and blush petals at every depth, clear of her face and the lettering.")
fam = L("family_lines")
add("s06-families", "scene-06", "Both families' blessing — floating over the ring pillow on the vestry table (top-down)", fam, False,
"No people. A STEEP HIGH ANGLE, about 65 degrees down, over a vestry table by a lancet window inside the church: an ivory lace runner on dark polished wood, an open ivory satin-and-lace RING PILLOW holding two plain gold wedding rings tied with a blush satin ribbon (no diamonds, no gemstones), a low arrangement of white and blush roses, lilies and baby's breath, two tall white candles in glass, and soft stained-glass colour falling across the lace, on a dynamic diagonal. Floating in the open air above the table, centred and filling most of the frame, in the razor-sharp focus plane: the headings in luminous calligraphy and the names in elegant serif, with clear spacing between the groom's parents group and the bride's parents group.",
lettering=LET(fam, "Headings ('With the Blessings of', \"Groom's Parents\", \"Bride's Parents\") in luminous gold calligraphy; the parents' names in elegant gold serif."))
cer = L("ceremony_lines")
add("s07-matrimony", "scene-07", "Holy Matrimony — couple at the altar, ceremony lines floating", cer, True,
"The couple and, far in the background, one small softly blurred priest. A creative low three-quarter angle from beside the front pew, looking up the white Gothic nave toward the altar with its plain cross, tall candles and lancet stained-glass windows: the couple stand facing each other at the altar step, holding both hands, gazing at each other with soft smiles, seen from about the knees up in the LEFT half of the frame. " + GROOM + " " + BRIDE.replace("Her bouquet:", "Her bouquet rests on the front pew:") +
" White-and-blush pew bows and ivory aisle runner lead to them; soft diagonal sunrays rake through the stained glass across the couple and haze. Floating on the RIGHT, in the open air at the same depth as the couple and razor-sharp: the ceremony lines, the first line in luminous calligraphy, the rest in elegant serif.",
lettering=LET(cer, "The first line in luminous gold calligraphy, the rest in elegant gold serif."))
add("s07b-ring-drop", "ADDED after scene-07", "ADDED: ring drop — the bride's hand drops two gold rings into the groom's palm (no text)", [], True,
"Only two HANDS (the bride's and the groom's), no faces. Vertical close-up, the moment just after the bride lets the rings fall. TOP RIGHT: the bride's hand enters from the right edge, palm down, fingers extended toward the left, natural skin with no henna or markings, a slim rose-gold bracelet at her wrist and the edge of white lace at her wrist only. CENTRE: TWO plain gold wedding rings tumble in MID-AIR, frozen in motion, slightly apart and at different tilts — one plain polished band and one slimmer engraved band, NO diamonds, NO gemstones — exactly in the razor-thin focus plane, crisp, with warm highlights. BOTTOM LEFT: the groom's open palm enters from the left edge, palm UP, ready to catch them; at his wrist the deep plum suit cuff over an ivory shirt cuff and the edge of his gold chronograph (plain dial, no numbers or logos). The fingertips and rings share the focus plane. A few white and blush petals frozen in mid-air around the rings. Background: the candlelit white nave and stained glass melted completely into creamy rose-blue-gold bokeh; a warm sunbeam from the upper right rim-lights the rings.")
ven = L("venue_lines")
add("s08-venue", "scene-08", "Venue — floating over the backwater, church facade across the water", ven, False,
"No people. A creative LOW angle from just above the water at the end of the decorated wooden boat jetty, looking across the rippling backwater at the white Kerala Gothic church facade on the far bank — gold gable cross, blue laurel medallion, lancet windows, pinnacle turrets, the white balustrade along the water — in soft creamy focus. In the near foreground, the jetty's edge with white-and-blush rose swags, an ivory ribbon and a glass lantern with a white candle. Floating in the open air above the water, large and centred, in the razor-sharp focus plane: the heading in luminous calligraphy and the venue lines in elegant serif. Soft late-morning sun slants from the left across gentle mist; the water mirrors the church and the floating letters' glow. Floating white and blush petals at every depth, clear of the lettering.",
lettering=LET(ven, "The first line in luminous gold calligraphy, the rest in elegant gold serif."))
rec = L("reception_lines")
add("s09-reception", "scene-09", "Reception — evening garden with the wedding cake stage, reception lines floating", rec, False,
"No foreground people (only a few softly blurred guests far in the background). BLUE-HOUR evening in the parish hall garden beside the backwater church, the white church facade glowing softly in the distance: a creative low three-quarter angle toward a small decorated reception stage under strings of warm fairy lights and hanging glass lanterns, an elegant ivory loveseat with blush cushions, sheer ivory drapes and a floral wall of white and blush roses; in the midground on a dressed table with an ivory lace runner, a three-tier white fondant wedding cake with delicate gold leaf, a plain gold interlocking double-ring topper (no diamond) and a cascade of white and blush roses, standing firmly on the table, with NO forks, plates, napkins or cutlery. Floating in the open air above the garden, large and clearly readable, in the razor-sharp focus plane: the first line in luminous calligraphy, the rest in elegant serif. Warm lamp pools and narrow light shafts through faint haze, deep teal-blue shadows; fairy lights and lanterns bloom into creamy bokeh orbs. Quiet suspended white and blush petals spread through the depth, clear of the lettering.",
lettering=LET(rec, "The first line in luminous gold calligraphy, the rest in elegant gold serif."))
host = L("host_lines")
add("s10-hosts", "scene-10", "Hosts — golden-hour garden arch, 'Invited By' lines floating", host, False,
"No people. Golden hour in the church garden: a creative low angle from the petal-strewn grass looking up through a tall white wedding arch dressed with white and blush roses, white lilies, baby's breath, trailing eucalyptus and sheer ivory drapes moving gently, glass lanterns with white candles hanging from it and standing at its feet; beyond, the white Gothic church's pinnacle turrets and gold gable cross glow in soft creamy bokeh against a warm peach sky. Floating in the open air within the arch, large and centred, in the razor-sharp focus plane: the first and last lines in luminous calligraphy, the names in elegant serif. Warm low sun from the left with soft god rays and long shadows. Floating white and blush petals at every depth, clear of the lettering.",
lettering=LET(host, "The first and last lines in luminous gold calligraphy, the names in elegant gold serif."))
sd = L("save_date_lines")
add("s11-save-date", "scene-11", "Save the date — couple on the decorated boat jetty, save-the-date lines floating", sd, True,
"Exactly two people, the couple. Soft sunrise on the decorated wooden boat jetty reaching into the backwater, the white Gothic church on the far bank in creamy bokeh: a creative low three-quarter angle from the jetty boards. The couple stand close together near the end of the jetty, the groom behind and slightly beside the bride with his arm gently around her waist, her hand resting on his, both smiling toward the camera, seen full length in the LEFT-CENTRE of the frame; white-and-blush rose swags and ivory ribbons on the jetty posts, glass lanterns with candles along the boards, a decorated wooden country boat with white flowers moored alongside. " + GROOM + " " + BRIDE +
" Floating on the RIGHT, in the open air at the same depth as the couple and razor-sharp, the save-the-date lines, stacked and centred, the first line slightly larger. Soft diagonal sunrise rays across the mist, glowing rim light on the couple and the gown, rippling reflections. Around 12 tiny separate petals at irregular heights.",
lettering=LET(sd, "The first line slightly larger; all lines in elegant gold display lettering."))
add("s12-forehead-touch", "scene-12", "Forehead touch — same jetty, save-the-date lines still floating (OG end frame)", sd, True,
"Exactly two people, the couple, at the SAME decorated jetty and the SAME floating save-the-date lines as the previous scene, a little closer: a creative low three-quarter angle. The couple face each other and gently touch foreheads, eyes closed, smiling softly, her hands resting on his chest, his hands lightly at her waist, seen from about the knees up in the LEFT-CENTRE of the frame; her cathedral veil drifts softly behind. " + GROOM + " " + BRIDE.replace("Her bouquet:", "Her bouquet, held low in one hand:") +
" The white Gothic church across the backwater in creamy bokeh, jetty swags and lanterns soft around them. Floating on the RIGHT, in the open air and razor-sharp, the same save-the-date lines. Golden sunrise rim light, rippling reflections, a few tiny petals at irregular heights.",
lettering=LET(sd, "The first line slightly larger; all lines in elegant gold display lettering."))
for k, v in S.items(): (OUT/f"still_{k}_prompt.txt").write_text(v["prompt"])
json.dump({k: {kk: vv for kk, vv in v.items() if kk != "prompt"} for k, v in S.items()}, open(OUT/"scenes.json", "w"), ensure_ascii=False, indent=2)
for k, v in S.items(): print(k, v["og_scene"], len(v["prompt"]), v["text"])
