#!/usr/bin/env python3
"""christian-v1: build 12 English Christian-wedding still prompts (text-only). Typography blocks are VERBATIM from the
Christian church wedding template v1 (/workspace/fmi-productions/kerala-christian-vtv-mood/template.json, 'kerala-christian-v1',
scene-02 floating blessing title, scene-04 groom calligraphy, scene-05 bride calligraphy, style block, clip text rule).
Characters: this project's 3D storybook look (groom bearded) in the template's Christian attire. No Hindu elements."""
import json
from pathlib import Path
R = Path(__file__).resolve().parents[2]; OUT = R/"scripts/christian-v1"
g4 = (R/"scripts/still_groom_v4_prompt.txt").read_text()
lens = g4[g4.index("CAMERA AND LENS"):g4.index("FLOWERS (abundant)")].strip()
for a, b in [("placed exactly on the Tamil lettering and the hero subject at that same depth", "placed exactly on the gold lettering and the hero subject at that same depth"),
             ("(lamp flames, fairy lights, hanging-lamp glints, brass highlights)", "(candle flames, fairy lights, chandelier glints, gold highlights)")]:
    assert lens.count(a) == 1, a; lens = lens.replace(a, b)

STYLE = ("A full-bleed portrait 9:16 frame of a 3D STORYBOOK illustration for an elegant Christian church WEDDING invitation. Soft, painterly 3D storybook look throughout, warm and charming: "
"gently rounded stylised forms, soft hand-painted-feeling textures, soft global illumination and feature-film polish, like a premium 3D animated storybook. Explicitly NOT photorealistic, NOT semi-real. "
"ONE consistent world: a graceful white Kerala-style Christian church and its grounds — cream-white plaster walls, soft laterite stone accents, tall arched windows with luminous stained glass in rose, gold and soft blue, "
"a modest bell tower topped by a simple cross, a nave with polished dark wooden pews, a simple altar with a plain cross, warm golden light. "
"Decor: white and blush-pink roses, white lilies, baby's breath and soft green foliage in fixed arrangements, aisle bouquets on the pew ends, ivory satin ribbons and sheer ivory drapes, tall white pillar candles in glass and gold candle stands, small crystal chandeliers and warm fairy lights. "
"Palette: ivory, cream, champagne gold, blush pink, soft white and warm wood, with gentle powder-blue shade. "
"DRAMATIC CHIAROSCURO: gentle warm back-and-side sunlight streams diagonally through arched windows and open bays, clearly visible soft volumetric god rays cutting through thin atmospheric haze; luminous rim light on ivory silk, lace, pearl and champagne-gold against cooler powder-blue shade. Very fine dust motes sparkle only inside the sunbeams. "
+ lens + " "
"PETALS: white and blush-pink rose petals float in MID-AIR at every depth, suspended as if in a slow-motion breeze: a few soft near-lens petals at the edges as foreground bokeh, crisp midground petals, tiny distant petals; every petal stays clear of the lettering and faces. No confetti cannon, no solid flower bunches in the air. All bouquets and garlands are fixed to their supports. "
"CHRISTIAN STYLING ONLY: no Hindu elements of any kind — no bindi, kumkum or forehead marks, no henna, no temple jewellery, no marigolds, no lotus, no jasmine strings, no brass oil lamps, no temple pillars, no kolam, no deity images or Hindu motifs. "
"Generate only from this text, no reference image. No watermark, interface, logos, duplicate people, extra signs or unintended words.")

# ---- typography, VERBATIM from Christian church wedding template v1 (kerala-christian-v1 template.json) ----
T_STYLE = "Gold lettering has illuminated beveled edges, warm restrained emissive bloom, luminous hairline flourishes and discrete pinpoint highlights; sharp readable counters."
T_TITLE = ("Exquisite ornate display lettering with graceful curved serifs, a gently arched first line, elegant varied stroke widths and modest flourishes. "
           "These are freestanding dimensional letters suspended in the open air, with luminous champagne-gold faces, antique-gold beveled edges, subtle warm halos and tiny bright edge glints. "
           "Rich gold, not brown engraving. No rectangular nameplate, printed wall text or letters attached to plaster. Readable counters and gaps between words, full title inside the frame.")
T_RULE = "Glowing lettering is solid beveled metal with light on its surface: no liquid gold, dripping strokes, ceiling-to-floor beams, explosive firework bursts or smoke emitted by text."
T_GROOM = "The gold letters have bright rim-lit beveled edges, gentle warm halos and a few tiny star-like glints along the flourishes, not a signboard."
T_BRIDE = "Bright golden bevels and soft warm halo, sharp readable letters."
ENG = "All text is ENGLISH, spelled exactly as quoted, character for character, each quoted line appearing exactly once; no other words, letters or numbers anywhere."
def lettering(extra=""):
    return "LETTERING: " + T_STYLE + " " + T_TITLE + " " + T_RULE + " " + ENG + (" " + extra if extra else "")
NOTEXT = "NO TEXT: absolutely no lettering, words, numbers, logos or signs anywhere in this image."

CHAR = ("CHARACTER STYLE: 3D storybook characters with a South Indian look: warm brown skin, appealing stylised facial design with soft skin and expressive eyes but grounded ADULT features; "
        "TALL adult proportions, about 7.5 heads tall with long legs — never chibi, never short or stubby, never child-like, never an oversized head. Correct anatomy: two arms, two hands, five fingers on each hand.")
GROOM = ("The GROOM: a handsome tall adult man with neat black hair, a FULL, neatly groomed short black BEARD and a moustache, and a confident warm smile; no forehead mark. "
         "He wears an ivory formal suit over a cream shirt with a soft white-and-pale-pink boutonniere (a small white rose with blush rosebud and baby's breath) on the left lapel, dark polished shoes, "
         "and on his wrist a stylish modern luxury chronograph watch in gold or polished steel (plain dial with no numbers, words or logos).")
BRIDE = ("The BRIDE: a beautiful tall adult woman with dark hair in an elegant low bun with a soft sheer ivory veil and small pearl pins, a soft warm smile, natural skin with no forehead mark and no henna. "
         "She wears an ivory lace-and-silk Christian wedding gown with soft cream undertones, fitted lace bodice and long sheer lace sleeves, a flowing skirt and train; a delicate gold cross pendant, pearl earrings and a slim pearl bracelet. "
         "She holds a bouquet of white and blush-pink roses, white lilies and baby's breath tied with an ivory satin ribbon.")

S = {}
S["c01-opening"] = dict(title="Opening — floral cross and church board 'With God's Grace'", text=["With God's Grace"], people=False, prompt=STYLE + "\n\n" +
"LETTERING (on the one church board): " + T_STYLE + " Exquisite ornate display lettering with graceful curved serifs, elegant varied stroke widths and modest flourishes, with luminous champagne-gold faces, antique-gold beveled edges, subtle warm halos and tiny bright edge glints. Rich gold, not brown engraving. Readable counters and gaps between words. " + T_RULE + " " + ENG + "\n\n" +
"""SCENE COMPOSITION (opening): No people. A creative LOW three-quarter angle inside the small open arched PORCH of the white church at sunrise, looking slightly up. CENTRE-LEFT, in the razor-sharp focus plane: a simple elegant CROSS made of white roses, white lilies and baby's breath with soft green foliage, standing on a low square cream stone pedestal between two tall white pillar candles in gold stands, flames glowing as creamy orbs. RIGHT of the cross, beside it at the same depth: ONE elegant church board — an ivory board with a fine carved champagne-gold frame and a tiny gold cross at its top, on a slim gold stand, facing the camera square-on, large in frame (about 45 percent of the frame width) — carrying exactly ONE line of large raised dimensional gold lettering: 'With God's Grace' (spelled exactly, with the apostrophe: W-i-t-h  G-o-d-'-s  G-r-a-c-e). This board is the only sign in the image. Behind, through the open arches, the cream-white bell tower with its cross and a soft blue-and-peach sunrise sky melt into creamy bokeh; white-and-blush floral swags hang on the porch arches. Warm sunrise god rays slant from the upper left through haze, rim-lighting the floral cross and the gold frame. Floating white and blush rose petals at every depth, clear of the lettering.""")
S["c02-title"] = dict(title="Title — 'Wedding Invitation' floating in the church nave", text=["Wedding", "Invitation"], people=False, prompt=STYLE + "\n\n" + lettering() + "\n\n" +
"""SCENE COMPOSITION (title): No people. A creative LOW angle from the floor of the centre aisle of the church nave, looking up toward the altar: polished dark wooden pews with white-and-blush rose aisle bouquets and ivory ribbons on the pew ends line both sides, a soft ivory aisle runner strewn with petals leads to the altar with its plain cross, tall arched stained-glass windows glow in rose, gold and soft blue, small crystal chandeliers and candles bloom into creamy bokeh orbs. In the upper-middle of the frame, a LARGE two-line floating title reads exactly 'Wedding' / 'Invitation'. The title spans approximately 65-70 percent of frame width, in the upper-middle quarter, separated clearly from the altar cross, in the razor-sharp focus plane. Soft sunlight strikes the letters obliquely through the stained glass and reflects softly in the polished floor. Floating white and blush rose petals at three depths, clear of the lettering.""")
S["c03-names"] = dict(title="Names — couple and parents, floating over the altar table", text=["Maniraj (Rajesh)", "S/o Mr. Nehru & Mrs. Shanthi,", "Thiruvannamalai", "&", "Keerthana", "D/o Mr. Shankar & Mrs. Usharani,", "Melchengam"], people=False, prompt=STYLE + "\n\n" + lettering("The two names are spectacular fine champagne-gold calligraphy in large flowing thin strokes; the parents' lines are smaller elegant serif lines in the same gold.") + "\n\n" +
"""SCENE COMPOSITION (names): No people. A steep, creative HIGH three-quarter angle over a church altar-side table dressed with an ivory satin runner and lace, a low arrangement of white and blush roses, white lilies and baby's breath, tall white pillar candles in glass, and an ivory satin ring pillow; arched stained-glass windows glow softly behind in creamy bokeh. Floating in the open air above the table, centred, filling most of the frame width, in the razor-sharp focus plane, in reading order, each line exactly once:
1) large calligraphy line exactly 'Maniraj (Rajesh)'
2) small serif line exactly 'S/o Mr. Nehru & Mrs. Shanthi,'
3) small serif line exactly 'Thiruvannamalai'
4) a small gold calligraphy ampersand exactly '&'
5) large calligraphy line exactly 'Keerthana'
6) small serif line exactly 'D/o Mr. Shankar & Mrs. Usharani,'
7) small serif line exactly 'Melchengam'
Generous spacing between the groom's group and the bride's group; every line fully inside the frame and readable. Warm sunbeams slant from the upper right through haze. Floating white and blush rose petals at every depth, clear of the lettering.""")
S["c04-groom"] = dict(title="The Groom — portrait with floating name", text=["The Groom", "Maniraj (Rajesh)"], people=True, prompt=STYLE + "\n\n" + CHAR + " Only ONE person in this frame: the groom.\n\n" + lettering(T_GROOM) + "\n\n" +
"SCENE COMPOSITION (groom — mirrored pair with the bride still: groom on the LEFT, floating text on the RIGHT, camera from the front-left): A creative LOW three-quarter angle from the front-LEFT at chest height, looking slightly up, inside a shaded cream-plaster side aisle of the church with tall arched stained-glass windows, white-and-blush floral swags and candle stands receding in creamy bokeh; soft sunrays enter through high LEFT arched windows. LEFT-CENTRE, seen from about the knees up, turned slightly toward the right and looking toward the camera: " + GROOM + " "
"Floating on the RIGHT at chest height, at the SAME depth as his face and in the razor-sharp focus plane, spectacular fine champagne-gold calligraphy reads exactly 'The Groom' on a small first line and 'Maniraj (Rajesh)' on a graceful large line below, each line exactly once. Floating white and blush rose petals at every depth, clear of the lettering and of his face.")
S["c05-bride"] = dict(title="The Bride — portrait with floating name", text=["The Bride", "Keerthana"], people=True, prompt=STYLE + "\n\n" + CHAR + " Only ONE person in this frame: the bride.\n\n" + lettering(T_BRIDE) + "\n\n" +
"SCENE COMPOSITION (bride — mirrored pair with the groom still: bride on the RIGHT, floating text on the LEFT, camera from the front-right): A creative LOW three-quarter angle from the front-RIGHT at chest height, looking slightly up, in a sunlit arched passageway of the church with tall arched stained-glass windows, white-and-blush floral swags and candle stands receding in creamy bokeh; soft sunbeams enter from the upper RIGHT. RIGHT-CENTRE, seen from about the knees up, turned slightly toward the left and looking toward the camera: " + BRIDE + " "
"On the LEFT, at chest height, at the SAME depth as her face and in the razor-sharp focus plane, floats a large exquisite luminous gold calligraphic title, exactly 'The Bride' in small type above 'Keerthana' in large flowing thin strokes, each line exactly once. Floating white and blush rose petals at every depth, clear of the lettering and of her face.")
S["c06-ring-plate"] = dict(title="Ring pillow — two gold rings on the altar (no text)", text=[], people=False, prompt=STYLE + "\n\n" + NOTEXT + "\n\n" +
"""SCENE COMPOSITION (rings): No people, no hands. A unique creative LOW three-quarter angle just above table height on the church altar table, looking slightly up. HERO, centre, in the razor-sharp focus plane: an ivory satin and lace ring pillow on a small engraved champagne-gold tray, holding TWO plain traditional gold wedding rings side by side, loosely tied with a thin blush-pink satin ribbon (no diamonds, no gemstones, no crystals, no stones of any kind). Around the tray: white and blush-pink roses, white lilies and baby's breath, an ivory lace runner, and tall white pillar candles in glass whose flames bloom into creamy orbs. Behind, the arched stained-glass windows and the plain altar cross dissolve into soft rose-gold-blue bokeh. Warm sunbeams slant from the upper right through haze, rim-lighting the gold rings. Floating white and blush rose petals at every depth, clear of the rings.""")
S["c07-ring-drop"] = dict(title="Ring drop — bride's hand drops two rings into the groom's palm (no text)", text=[], people=True, prompt=STYLE + "\n\n" + NOTEXT + "\n\n" +
"""CHARACTER STYLE: only two HANDS appear (the bride's and the groom's), in the same 3D storybook character style: warm brown skin, graceful ADULT hands with correct anatomy — exactly five fingers on each hand, natural knuckles and nails, no extra or fused fingers. No faces, no full figures, no other people.

SCENE COMPOSITION (ring drop, vertical close-up, the moment just after the bride lets the rings fall):
TOP RIGHT: the BRIDE's hand enters from the right edge, palm down, fingers extended gracefully toward the left. Her hand is natural and clean, NO henna, NO mehndi, no markings; she wears a slim pearl bracelet and a delicate gold band. Her forearm is BARE right to the frame edge: NO sleeve, NO fabric of any kind on the bride's arm.
CENTRE, just below her fingertips: TWO plain traditional gold wedding rings tumble in MID-AIR, frozen in motion, slightly apart and at different tilts — one plain polished gold band and one slimmer gold band with fine engraving. Plain gold ONLY: NO diamonds, NO gemstones, NO crystals. Both rings sit exactly in the razor-thin focus plane, crisp, with warm golden highlights along their edges.
BOTTOM LEFT: the GROOM's hand enters from the left edge, palm UP and open, fingers relaxed and slightly curved, ready to catch the falling rings. At his wrist the cuff of his ivory suit jacket over a cream shirt cuff, and just under it the edge of his stylish luxury chronograph watch (plain dial with no numbers, words or logos).
The fingertips of both hands and the two rings share the razor-sharp focus plane; the forearms soften gently away from it. A few white and blush rose petals frozen in mid-air around the rings.
BACKGROUND: the warm golden church interior melted completely into creamy, smudged Noctilux bokeh: large soft glowing candle orbs, rose-gold-blue stained-glass glow, ivory and blush floral blurs, hints of warm wood. A warm golden sunbeam slants in from the upper right through soft haze, giving golden rim light on the rings and fingertips.""")
S["c08-date"] = dict(title="Date and time — floating over the church aisle", text=["Monday, 12 October 2026", "12:00 PM – 1:30 PM"], people=False, prompt=STYLE + "\n\n" + lettering() + "\n\n" +
"""SCENE COMPOSITION (date and time): No people. A creative low angle from beside a pew end decorated with a white-and-blush rose bouquet and an ivory satin bow, looking diagonally across the candlelit aisle toward the altar: rows of dark wooden pews, tall white pillar candles along the aisle, arched stained-glass windows glowing behind in creamy bokeh, a small crystal chandelier above. Floating in the open air above the aisle, large and centred, in the razor-sharp focus plane, exactly TWO lines, each exactly once:
1) large line exactly 'Monday, 12 October 2026'
2) slightly smaller line exactly '12:00 PM – 1:30 PM' (with an en dash between the two times)
Warm sunbeams slant through the stained glass from the upper left. Floating white and blush rose petals at every depth, clear of the lettering.""")
S["c09-venue"] = dict(title="Venue — floating over the decorated entrance archway", text=["Venue", "Annai Manimegalai Thirumana Mandapam", "Chengam"], people=False, prompt=STYLE + "\n\n" + lettering() + "\n\n" +
"""SCENE COMPOSITION (venue): No people. A creative low three-quarter angle toward a grand decorated wedding entrance: a tall cream-white arched doorway with carved double doors standing open, framed by a lush arch of white and blush roses, white lilies, baby's breath and soft greenery, ivory drapes, tall white pillar candles in glass lanterns lining the steps, warm light glowing from inside; the bell tower with its cross softly in the background bokeh. Floating in the open air in front of the archway, in the razor-sharp focus plane, exactly THREE lines, centred, each exactly once:
1) small line exactly 'Venue'
2) large line exactly 'Annai Manimegalai Thirumana Mandapam' (may wrap across two lines as 'Annai Manimegalai' / 'Thirumana Mandapam', every letter exact)
3) medium line exactly 'Chengam'
Warm late-afternoon sunbeams slant from the upper right through haze. Floating white and blush rose petals at every depth, clear of the lettering.""")
S["c10-closing-1"] = dict(title="Closing 1 — 'Your presence is our blessing'", text=["Your presence", "is our blessing"], people=False, prompt=STYLE + "\n\n" + lettering() + "\n\n" +
"""SCENE COMPOSITION (closing 1): No people. A creative low angle in the open church doorway looking out to a sunlit garden path lined with white and blush rose arrangements and glass lanterns with white candles; in the foreground, the end of a dark wooden pew with a white-and-blush bouquet and an ivory satin ribbon; tall arched doorframe with floral swags. Floating in the open air in the doorway, large and centred, in the razor-sharp focus plane, exactly TWO lines, each exactly once:
1) line exactly 'Your presence'
2) line exactly 'is our blessing'
Golden sunbeams stream in through the doorway toward the camera through soft haze. Floating white and blush rose petals at every depth, clear of the lettering.""")
S["c11-closing-2"] = dict(title="Closing 2 — 'With love, from both families'", text=["With love,", "from both families"], people=False, prompt=STYLE + "\n\n" + lettering() + "\n\n" +
"""SCENE COMPOSITION (closing 2): No people. A creative low angle in the church garden at golden hour: a white floral wedding arch of white and blush roses, white lilies, baby's breath and ivory drapes over a petal-strewn path, white candles in glass lanterns at its feet, the white church and its bell tower with a cross glowing warmly beyond in creamy bokeh. Floating in the open air under the arch, large and centred, in the razor-sharp focus plane, exactly TWO lines, each exactly once:
1) line exactly 'With love,'
2) line exactly 'from both families'
Warm golden sunset light slants from the left with soft god rays. Floating white and blush rose petals at every depth, clear of the lettering.""")
S["c12-finale"] = dict(title="Grand finale — couple exchanging rings on the decorated stage, MK cake", text=["Maniraj & Keerthana (backdrop, out of focus)", "MK (cake monogram, out of focus)"], people=True, prompt=STYLE.replace("a razor-thin plane of focus placed exactly on the gold lettering and the hero subject at that same depth", "a shallow plane of focus placed on the couple") + "\n\n" + CHAR + " TWO people only, the couple; no guests or other figures.\n\n" +
"LETTERING: the only lettering is the names on the far backdrop and a small gold 'MK' monogram on the cake, BOTH softly out of focus, soft gold shapes in the bokeh; legibility is not required. " + T_STYLE + " No other words, numbers or logos anywhere.\n\n" +
"SCENE COMPOSITION (GRAND FINALE — the ring exchange): A calm, clean grand-finale shot from a creative, slightly LOW angle on a decorated wedding stage at the front of an elegant hall in the church grounds in the evening: soft crystal chandeliers, warm fairy lights, tall white candles, a few large simple arrangements of white and blush roses, lilies and baby's breath, sheer ivory drapes. The focus falls off GRADUALLY and naturally with distance like a real fast portrait lens in a feature-film 3D animated movie: decor just behind the couple only slightly soft, the far backdrop and lights melting smoothly into creamy bokeh; no halo or cut-out edge around the couple; the couple share the same warm lighting and colour as the room. "
"CENTRE, the ONE clear subject, camera ZOOMED IN to about knees-up (three-quarter length), the couple filling most of the frame in natural sharp focus: they stand physically CLOSE together, shoulders nearly touching, facing each other and turned three-quarter toward the camera, in the intimate ring-exchange moment — the bride gently slips a plain gold wedding ring (no diamond, no stone) onto the groom's ring finger, their hands together between them at chest height, both smiling warmly. " + GROOM + " " + BRIDE.replace("She holds a bouquet", "Her bouquet") .replace("tied with an ivory satin ribbon.", "tied with an ivory satin ribbon rests on the table beside the cake.") + " "
"BEHIND THEM, softly out of focus: an elegant ivory loveseat with gold trim and blush cushions, and a floral backdrop wall of white and blush roses with sheer drapes carrying the names 'Maniraj & Keerthana' in gold lettering, soft and not readable. "
"FOREGROUND, only PARTLY visible at the lower LEFT corner, soft as foreground bokeh: the edge of a table with a visible table surface and an ivory lace runner, and a three-tier white fondant wedding cake with delicate gold leaf standing clearly ON the table (never floating), its small gold 'MK' monogram, a plain gold interlocking double-ring topper (no diamond) and a cascade of white and blush roses with baby's breath reading only as soft shapes. ABSOLUTELY NO forks, knives, plates, napkins, glasses or cutlery. "
"A gentle, sparse, soft-focus drift of gold confetti and white and blush rose petals floats in from the SIDE toward the couple, frozen mid-air, none covering their faces or hands. Calm, elegant and joyful.")

for k, v in S.items():
    (OUT/f"still_{k}_prompt.txt").write_text(v["prompt"])
json.dump({k: {kk: vv for kk, vv in v.items() if kk != "prompt"} for k, v in S.items()}, open(OUT/"scenes.json", "w"), ensure_ascii=False, indent=2)
for k, v in S.items():
    p = v["prompt"]; bad = [w for w in ["Tamil","kumkum","marigold","lotus","jasmine","Chettinad","temple","brass","mehndi","henna","kolam","saree"] if w.lower() in p.lower()]
    print(k, len(p), "mentions(neg ok):", bad)
