#!/usr/bin/env python3
"""christian-v3 (christian_remix_v3): exact replacements on scripts/christian-v2/still_*_prompt.txt.
Ooty / Nilgiri hills with clouds and mist; tall standing cross (never lantern-formed/flat); much more depth (long hallways, arcades, tree avenues into mist).
Text, couple, outfits, typography, style and lens blocks unchanged from v2."""
import json, re
from pathlib import Path
R = Path(__file__).resolve().parents[2]; V2 = R/"scripts/christian-v2"; OUT = R/"scripts/christian-v3"
SC = json.load(open(V2/"scenes.json"))
def rep(t, a, b):
    n = t.count(a); assert n == 1, (n, a[:100]); return t.replace(a, b)
s11 = (V2/"still_s11-save-date_prompt.txt").read_text()
GROOM = re.search(r"The GROOM \(identical wherever he appears\):.*?\(plain dial with no numbers, words or logos\)\.", s11, re.S).group(0)
BRIDE = re.search(r"The BRIDE \(identical wherever she appears\):.*?tied with a blush satin ribbon\.", s11, re.S).group(0)

OLD_CHURCH = ("CHURCH (the one main church, exterior and matching interiors): a white Kerala Gothic church facade beside a backwater, with a central pointed gable topped by a gold cross, a round blue medallion with a green laurel wreath set in the gable, "
 "tall pointed lancet windows with grey trim, slender white pinnacle turrets each topped by a small cross, and grey-outlined geometric chevron details; it stands behind a white balustrade fence along the water's edge, "
 "with terracotta-tiled roofs beside it and a red-roofed building nearby, coconut palms, soft sky and rippling water reflections. Its interior matches: white pointed Gothic arches, lancet stained-glass windows in soft blue, rose and gold, polished dark wooden pews, a simple altar with a plain cross.")
NEW_CHURCH = ("LOCATION: Ooty in the Nilgiri hills: misty hillsides with rolling green tea-estate slopes, tall eucalyptus and pine trees, low drifting clouds and soft mist, cool pearly overcast light warmed by gentle golden highlights; the misty Ooty Lake with pines on its banks. "
 "CHURCH (the one main church, exterior and matching interiors): a white Kerala-Gothic-style church set on a misty hillside in Ooty, with a central pointed gable topped by a gold cross, a round blue medallion with a green laurel wreath set in the gable, "
 "tall pointed lancet windows with grey trim, slender white pinnacle turrets each topped by a small cross, and grey-outlined geometric chevron details; a white balustrade terrace in front of it, tea-estate slopes, eucalyptus and pines around it and low clouds drifting behind. "
 "Its interior matches: LONG white nave and side hallways with repeating pointed Gothic arches and slender pillars receding far into the distance, lancet stained-glass windows in soft blue, rose and gold, polished dark wooden pews, a simple altar with a plain standing cross. "
 "CROSS RULE: every cross is a solid, upright, freestanding cross standing tall — never lying flat, never formed by lanterns or candles on the ground, never tilted; an upright cross is visible somewhere in every scene, small and natural, often soft in the bokeh. "
 "DEPTH RULE: every scene has deep, open space behind the subjects — long receding hallways, nave corridors, cloister walkways with repeating arches and pillars, long aisles, or avenues of trees fading into mist — clearly layered foreground, midground and far background, with mist adding atmospheric depth that reads as soft layered bokeh.")
GLOBAL = [("intimate coastal Kerala atmosphere", "intimate misty Nilgiri hill-station atmosphere"),
          ("pale pink florals and cool backwaters haze beyond coconut palms.", "pale pink florals and cool drifting mist and low clouds over green tea-estate slopes, eucalyptus and pines."),
          ("ONE white Kerala Gothic church beside a calm backwater (see CHURCH below).", "ONE white Kerala-Gothic-style church on a misty Ooty hillside (see CHURCH below)."),
          ("clearly visible soft volumetric god rays cutting through thin coastal atmospheric haze;", "clearly visible soft volumetric god rays cutting through thin misty mountain air;"),
          (OLD_CHURCH, NEW_CHURCH)]
NEW = {}
NEW["s01-aerial"] = ("No people except a few tiny distant figures with no detail. A high oblique DRONE establishing shot over the Nilgiri hills of Ooty, the camera about 40 metres up and well back, looking diagonally down at about 20-25 degrees across layered misty ridges: in the middle distance the white Kerala-Gothic-style church stands on a green hillside terrace — pointed gable with the upright gold cross, blue laurel medallion, lancet windows, pinnacle turrets with small crosses, the white balustrade terrace — framed by tall eucalyptus and pines. Rolling tea-estate slopes with neat rows curve away below; a long winding tree-lined avenue decorated with white-and-blush rose swags and lanterns leads up to the church; beyond it, ridge after ridge fades into low drifting clouds, and the misty Ooty Lake glints far below. Soft early light: cool pearly overcast sky with gentle golden highlights breaking through the clouds. Huge sense of depth and open space, layered mist between every ridge. Decorations stay small in the landscape. No text.")
NEW["s02-blessing"] = ("No people. A misty hilltop terrace beside the church at soft dusk: a creative LOW angle almost at stone level, looking up at a TALL, solid, upright freestanding CROSS of carved white stone with fine gold inlay edges, standing straight on a stepped white stone plinth (never lying flat, never tilted, never formed by lanterns), clusters of white candles in glass lanterns glowing at its base with a few white-and-blush roses and eucalyptus. Behind it a long white balustrade recedes into the distance along the terrace edge, then misty tea-estate slopes, rows of tall pines and ridge after ridge fading into low glowing clouds; the white Gothic church with its gold gable cross sits far back and soft in the mist. Above the cross, in the upper-middle quarter, a LARGE two-line floating blessing title, spanning about 65-70 percent of frame width, separated clearly from the top of the cross, in the razor-sharp focus plane with the cross. Warm candle glow and a last golden light through the clouds strike the letters. A few white and blush petals float at three depths, clear of the lettering and the cross. Deep layered space and mist behind.")
NEW["s03-invitation"] = ("No people. A creative HIGH three-quarter angle from the top of the church steps, looking across the open carved wooden double doors of the white Gothic church and deep into its interior: a LONG nave corridor of repeating white pointed arches and slender pillars recedes far into the distance toward the altar and its small upright cross, lined with pews with white-and-blush bows and tall candles, soft mist and light shafts in the depth. Outside, the white steps are lined with tall white candles in glass lanterns and white-and-blush rose arrangements with eucalyptus, ivory ribbons on the door handles, petals on the steps, misty pines at the edges. Floating in the open air in front of the doorway, large and centred, in the razor-sharp focus plane. The first line is graceful expressive calligraphy, the lower line elegant wedding display lettering, all fully within generous margins. Cool pearly morning light with warm golden beams slanting from the upper left through the mist. Floating white and blush petals at every depth, clear of the lettering.")
NEW["s04-groom"] = ("Only ONE person, the groom. A creative LOW three-quarter angle from the front-LEFT at chest height, looking slightly up, on the long white balustrade terrace of the hillside church in misty morning light: the groom leans relaxed with one hand on the white balustrade and the other in his trouser pocket, his watch visible, turned slightly toward the right and smiling toward the camera, seen from about the knees up, in the LEFT half of the frame. " + GROOM +
 " Behind him the balustrade and a row of lanterns recede far into the distance along the terrace, past the church's pinnacle turrets and its upright gold gable cross, then misty tea-estate slopes and pines fading ridge after ridge into low clouds — lots of open, layered space melting into creamy bokeh; white-and-blush rose swags with ivory ribbons on the balustrade. Floating on the RIGHT at chest height, at the same depth as his face and razor-sharp, spectacular fine champagne-gold calligraphy: a small first line and a graceful large line below. The gold letters have bright rim-lit beveled edges, gentle warm halos and a few tiny star-like glints along the flourishes, not a signboard. Floating white and blush petals at every depth, clear of his face and the lettering.")
NEW["s05-bride"] = ("Only ONE person, the bride. A creative LOW three-quarter angle from the front-RIGHT at chest height, looking slightly up, in a LONG white Gothic side hallway of the church: the bride stands beside a tall pointed lancet stained-glass window, turned three-quarter toward the left, holding her bouquet at her waist with both hands, glancing over her bare shoulder toward the camera with a soft smile, seen from about the knees up, in the RIGHT half of the frame, her cathedral veil flowing behind her. " + BRIDE +
 " Behind her the hallway recedes far into the distance: repeating white pointed arches, slender pillars and lancet windows in a long perspective, pew-end bows and tall candles, soft mist and light shafts, a small upright cross at the far end, all melting into layered creamy bokeh; outside the windows, misty pines and clouds. Coloured light from the stained glass falls softly across the white tulle. On the LEFT, at chest height, at the same depth as her face and razor-sharp, floats a large exquisite luminous gold calligraphic title, small type above a large name in flowing thin strokes. Bright golden bevels and soft warm halo, sharp readable letters. Floating white and blush petals at every depth, clear of her face and the lettering.")
NEW["s06-families"] = ("No people. A creative HIGH three-quarter angle, about 50 degrees down, over a vestry table set at the near end of a LONG white cloister walkway of the church: an ivory lace runner on dark polished wood, an open ivory satin-and-lace RING PILLOW holding two plain gold wedding rings tied with a blush satin ribbon (no diamonds, no gemstones), a low arrangement of white and blush roses, lilies and baby's breath, two tall white candles in glass, and a small upright gold standing cross; beyond the table the cloister's repeating pointed arches and pillars recede far into the distance, opening onto misty tea slopes and pines, layered in soft bokeh. Floating in the open air above the table, centred and filling most of the frame, in the razor-sharp focus plane: the headings in luminous calligraphy and the names in elegant serif, with clear spacing between the groom's parents group and the bride's parents group. Cool pearly light with soft golden highlights.")
NEW["s07-matrimony"] = ("The couple and, far in the background, one small softly blurred priest. A creative low three-quarter angle from beside a pew halfway down a VERY LONG white Gothic nave: repeating pointed arches and slender pillars recede in deep perspective toward the distant altar with its tall upright cross, tall candles and lancet stained-glass windows, soft mist and light shafts filling the depth. In the midground, at the altar step end of the aisle, the couple stand facing each other holding both hands, gazing at each other with soft smiles, seen from about the knees up in the LEFT half of the frame, with lots of open space and receding arches behind them. " + GROOM + " " + BRIDE.replace("Her bouquet:", "Her bouquet rests on the front pew:") +
 " White-and-blush pew bows and an ivory aisle runner lead toward them; soft diagonal rays rake through the stained glass. Floating on the RIGHT, in the open air at the same depth as the couple and razor-sharp: the ceremony lines, the first line in luminous calligraphy, the rest in elegant serif.")
NEW["s07b-ring-drop"] = ("Only two HANDS (the bride's and the groom's), no faces. Vertical close-up, the moment just after the bride lets the rings fall. TOP RIGHT: the bride's hand enters from the right edge, palm down, fingers extended toward the left, natural skin with no henna or markings, a slim rose-gold bracelet at her wrist and the edge of white lace at her wrist only. CENTRE: TWO plain gold wedding rings tumble in MID-AIR, frozen in motion, slightly apart and at different tilts — one plain polished band and one slimmer engraved band, NO diamonds, NO gemstones — exactly in the razor-thin focus plane, crisp, with warm highlights. BOTTOM LEFT: the groom's open palm enters from the left edge, palm UP, ready to catch them; at his wrist the deep plum suit cuff over an ivory shirt cuff and the edge of his gold chronograph (plain dial, no numbers or logos). The fingertips and rings share the focus plane. A few white and blush petals frozen in mid-air around the rings. Background: a LONG white Gothic nave receding far behind the hands — repeating arches, candle rows and a small upright altar cross at the far end — melted into deep layered creamy bokeh with soft mist; a warm golden beam from the upper right rim-lights the rings.")
NEW["s08-venue"] = ("No people. A creative LOW angle from just above the water at the end of a long wooden jetty on misty Ooty Lake: the jetty's weathered boards and posts with white-and-blush rose swags, ivory ribbons and glass lanterns recede behind the camera's side; across the calm lake, tall pines line the far bank and low clouds drift over layered green hills, with the white Gothic church and its upright gold gable cross small and soft on a hillside in the far distance; a decorated wooden rowing boat with white flowers moored at the jetty. Floating in the open air above the water, large and centred, in the razor-sharp focus plane: the heading in luminous calligraphy and the venue lines in elegant serif. Cool pearly light with gentle golden highlights, mist drifting on the water, the lake mirroring the pines and the letters' glow. Deep layered space into the mist. Floating white and blush petals at every depth, clear of the lettering.")
NEW["s09-reception"] = ("No foreground people (only a few softly blurred guests far in the background). Blue-hour evening in a misty hill garden beside the church: a creative low three-quarter angle down a LONG garden avenue lined with tall pines and strings of warm fairy lights and hanging glass lanterns receding far into the mist, toward a small decorated reception stage with an elegant ivory loveseat with blush cushions, sheer ivory drapes and a floral wall of white and blush roses; a small upright white cross stands softly in the garden. In the near midground on a dressed table with an ivory lace runner, a three-tier white fondant wedding cake with delicate gold leaf, a plain gold interlocking double-ring topper (no diamond) and a cascade of white and blush roses, standing firmly on the table, with NO forks, plates, napkins or cutlery. Floating in the open air above the garden, large and clearly readable, in the razor-sharp focus plane: the first line in luminous calligraphy, the rest in elegant serif. Warm lamp pools and soft light shafts through the mist, deep cool blue shadows; fairy lights and lanterns bloom into layered creamy bokeh orbs. Quiet suspended white and blush petals spread through the depth, clear of the lettering.")
NEW["s10-hosts"] = ("No people. A misty hill garden at golden hour: a creative low angle from the petal-strewn path looking up through a SERIES of white wedding arches receding far into the distance, each dressed with white and blush roses, white lilies, baby's breath, trailing eucalyptus and sheer ivory drapes, glass lanterns with white candles hanging from them and lining the path; tall pines on both sides, and at the far end of the avenue the white Gothic church with its upright gold gable cross soft in the mist under low glowing clouds. Floating in the open air within the nearest arch, large and centred, in the razor-sharp focus plane: the first and last lines in luminous calligraphy, the names in elegant serif. Warm low golden sun breaking through the clouds from the left with soft god rays through the mist. Floating white and blush petals at every depth, clear of the lettering.")
NEW["s11-save-date"] = ("Exactly two people, the couple. Soft misty morning on a long wooden jetty on Ooty Lake: a creative low three-quarter angle from the jetty boards, the jetty and its posts with white-and-blush rose swags, ivory ribbons and glass lanterns receding far behind the couple into the mist, the calm lake with pines on the banks and layered hills disappearing into low clouds, the white Gothic church with its upright gold gable cross small and soft on a far hillside. The couple stand close together, the groom behind and slightly beside the bride with his arm gently around her waist, her hand resting on his, both smiling toward the camera, seen full length in the LEFT-CENTRE of the frame, with lots of open space behind them; a decorated wooden rowing boat with white flowers moored alongside. " + GROOM + " " + BRIDE +
 " Floating on the RIGHT, in the open air at the same depth as the couple and razor-sharp, the save-the-date lines, stacked and centred, the first line slightly larger. Cool pearly light with gentle golden rim light on the couple and the gown, rippling reflections, mist drifting on the water. Around 12 tiny separate petals at irregular heights.")
NEW["s12-forehead-touch"] = ("Exactly two people, the couple, at the SAME long misty jetty on Ooty Lake and the SAME floating save-the-date lines as the previous scene, a little closer: a creative low three-quarter angle. The couple face each other and gently touch foreheads, eyes closed, smiling softly, her hands resting on his chest, his hands lightly at her waist, seen from about the knees up in the LEFT-CENTRE of the frame; her cathedral veil drifts softly behind. " + GROOM + " " + BRIDE.replace("Her bouquet:", "Her bouquet, held low in one hand:") +
 " Behind them the jetty and lanterns recede far into the mist, pines and layered hills fade into low clouds, the white church with its upright gold cross small and soft in the distance. Floating on the RIGHT, in the open air and razor-sharp, the same save-the-date lines. Gentle golden light through the mist, rippling reflections, a few tiny petals at irregular heights.")
meta = {}
for sid in SC:
    t = (V2/f"still_{sid}_prompt.txt").read_text()
    for a, b in GLOBAL: t = rep(t, a, b)
    i = t.index("\n\nSCENE COMPOSITION:\n") + len("\n\nSCENE COMPOSITION:\n"); old = t[i:]
    t = rep(t, "\n\nSCENE COMPOSITION:\n" + old, "\n\nSCENE COMPOSITION:\n" + NEW[sid])
    for bad in ["backwater", "Alappuzha", "coconut", "terracotta", "red-roofed", "candle lanterns set in a precise cross"]:
        if bad.lower() in t.lower():
            # venue/reception lettering lines legitimately contain 'Near Alappuzha' (OG text) — allow only inside the LETTERING block
            pre = t[:t.index("SCENE COMPOSITION")]; comp = t[t.index("SCENE COMPOSITION"):]
            assert bad.lower() not in comp.lower() and (bad == "Alappuzha" and "exactly '" in pre), (sid, bad)
    (OUT/f"still_{sid}_prompt.txt").write_text(t); meta[sid] = {**SC[sid], "version": "christian-v3"}
    print(sid, len(t))
json.dump(meta, open(OUT/"scenes.json", "w"), ensure_ascii=False, indent=2)
