#!/usr/bin/env python3
import json, difflib, re
from pathlib import Path
R = Path(__file__).resolve().parent.parent
old = json.load(open(sorted((R/'packets').glob('storyboard.before-rev4-noctilux-*.json'))[-1]))
new = json.load(open(R/'storyboard.json'))
L = ["# PARAMETER DIFF REPORT — Revision 4 (Noctilux look, creative angles, golden type, flowers, rings, feathers)", "",
     "Backups: packets/*.before-rev4-noctilux-20261007-231835.* ; previous report: packets/PARAMETER_DIFF_REPORT.rev3-final.md",
     "Earlier stopped attempts (t9u/t11u) left only backups (*.before-rev4-lens-20261007-230146.*, byte-identical to the rev3 state) and packets/PARAMETER_DIFF_REPORT.rev3.md (a copy of the rev3 report). Nothing was generated by them.",
     "Authorised by Ashok (t9u, t11u, t13u, t14u, t15u): camera/lens, angles, typography, flowers, two ring boxes, peacock feathers. Text-only prompts; no image passed to the generator.", "",
     "## parameters", ""]
ch = [k for k in set(old['parameters']) | set(new['parameters']) if old['parameters'].get(k) != new['parameters'].get(k)]
L.append("No parameter changes." if not ch else str(ch))
L += ["", "## Shared STYLE", "", "- Replaced 'NOT painterly' with 'no painted brushwork' (bokeh is described as painterly/creamy per Ashok).",
      "- Replaced the 12-20 rose petals sentence with CAMERA AND LENS (Noctilux-M 75mm f/1.25 ASPH, DS, razor-thin focus on lettering, creamy soft-edged bokeh orbs, foreground bokeh, unique angle) + FLOWERS (abundant rose petals + orange/yellow marigolds at all depths and on the floor, clear of text).",
      "- LETTERING now: golden, reflective, decorative (polished embossed mirror-gold, bevel glints, separate filigree flourishes that never alter letters); reflective gold foil/gilded relief on card/sign; always in sharpest focus.",
      "- {{particles}} line: abundant petals + marigolds in foreground, midground, background and on the floor.", "",
      "## Scenes", "", "| scene | camera before | camera after | text unchanged |", "|---|---|---|---|"]
for o, n in zip(old['scenes'], new['scenes']):
    same = [t['resolved'] for t in o['text_fields']] == [t['resolved'] for t in n['text_fields']]
    L.append(f"| {n['id']} | {o['camera']} | {n['camera']} | {'yes' if same else 'NO'} |")
L += ["", "Prop additions: scene-03 TWO open ring boxes each with one gold ring (was one box); peacock feathers in scenes 02, 03, 04, 07; scene-01 now names the carved entrance porch + open doorway (already present in the approved rev3 still, needed by clip-01).", "",
      "## Clips", "", "Video prompts: unchanged in this step (update deferred until after the Telegram album, per parent instruction).", "",
      "## Resolved image prompts (rev 4)", ""]
for n in new['scenes']:
    L += [f"### {n['id']} ({len(n['image_prompt'])} chars)", "```text", n['image_prompt'], "```", ""]
(R/'PARAMETER_DIFF_REPORT.md').write_text("\n".join(L) + "\n")
cp = R/'packets/PARAMETER_DIFF_REPORT.rev4.md'; cp.write_text("\n".join(L) + "\n"); print("ok")
