import test from 'node:test';
import assert from 'node:assert/strict';
import handler from '../api/invitations.mjs';
import {tokenHash} from '../server/core.mjs';
import {db} from '../server/core.mjs';
const token='ab'.repeat(32);
const record={id:'00000000-0000-0000-0000-000000000001',slug:'test-couple',data:{bride:'Bride',groom:'Groom',sections:{rsvp:true}},published:true,expires_at:'2099-01-01T00:00:00Z',management_hash:tokenHash(token)};
async function request(url,authorization){const res={headers:{},setHeader(k,v){this.headers[k]=v;},status(n){this.code=n;return this;},json(b){this.body=b;}};await handler({url,method:'GET',headers:authorization?{authorization}:{}},res);return res;}
test('public DTO excludes secret, private routes reject wrong token, expired public reads fail',async()=>{const oldFetch=global.fetch,oldEnv={...process.env};process.env.SUPABASE_URL='https://example.supabase.co';process.env.SUPABASE_SERVICE_ROLE_KEY='test-service';process.env.RATE_LIMIT_SECRET='test-rate-secret-01234567890123456789';let row={...record};global.fetch=async()=>new Response(JSON.stringify([row]),{status:200});try{const read=await request('/api/invitations?action=read&slug=test-couple');assert.equal(read.code,200);assert.equal(JSON.stringify(read.body).includes(record.management_hash),false);assert.equal((await request('/api/invitations?action=manage&slug=test-couple','Bearer '+'cd'.repeat(32))).code,403);assert.equal((await request('/api/invitations?action=manage&slug=test-couple','Bearer '+token)).code,200);row={...record,published:false};assert.equal((await request('/api/invitations?action=read&slug=test-couple')).code,404);row={...record,expires_at:'2020-01-01T00:00:00Z'};assert.equal((await request('/api/invitations?action=read&slug=test-couple')).code,404);assert.equal((await request('/api/invitations?action=manage&slug=test-couple','Bearer '+token)).code,200);}finally{global.fetch=oldFetch;for(const key of Object.keys(process.env))if(!(key in oldEnv))delete process.env[key];Object.assign(process.env,oldEnv);}});
test('unconfigured API fails closed rather than accepting local storage',async()=>{const old=process.env.SUPABASE_URL;delete process.env.SUPABASE_URL;try{const res=await request('/api/invitations?action=read&slug=test-couple');assert.equal(res.code,503);const config=await request('/api/invitations?action=config');assert.equal(config.body.configured,false);assert.ok(config.body.serverNow);}finally{if(old!==undefined)process.env.SUPABASE_URL=old;}});
test('PostgREST minimal successful writes have no JSON body',async()=>{const oldFetch=global.fetch,oldEnv={...process.env};Object.assign(process.env,{SUPABASE_URL:'https://example.supabase.co',SUPABASE_SERVICE_ROLE_KEY:'test',RATE_LIMIT_SECRET:'test-rate-secret-01234567890123456789'});global.fetch=async()=>new Response(null,{status:201});try{assert.equal(await db('responses',{method:'POST',body:{}}),null);}finally{global.fetch=oldFetch;for(const key of Object.keys(process.env))if(!(key in oldEnv))delete process.env[key];Object.assign(process.env,oldEnv);}});

