// GrapesJS owns the canvas, selection, layers, style manager and undo stack.
// The original styles and approved scripts remain separate from its HTML parser.
export type Design={id:string;base_id:string;name:string;description:string;collection:string;thumbnail:string;html:string;assets:Record<string,string>;revision:number;published_revision:number|null};
export const mediaPattern=/\/assets\/[a-zA-Z0-9_./-]+\.(?:png|jpe?g|webp|gif|svg|mp4|webm|mp3|wav|ogg|woff2?)(?:#t=[0-9.]+)?/gi;
export const mediaList=(html:string)=>[...new Set(html.match(mediaPattern)||[])];
export async function request<T>(action:string,id?:string,body?:unknown):Promise<T>{const r=await fetch('/api/workspace?action='+action+(id?'&id='+encodeURIComponent(id):''),{method:body===undefined?'GET':'POST',headers:body===undefined?{}:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});let value;try{value=await r.json()}catch{throw Error('Workspace could not connect. Your changes are still in this tab.');}if(!r.ok)throw Error(value.error||'Workspace request failed.');return value;}
export async function loadGrapes(){if((window as any).grapesjs)return (window as any).grapesjs;await new Promise<void>((resolve,reject)=>{const css=document.createElement('link');css.rel='stylesheet';css.href='/vendor/grapesjs/grapes.min.css';document.head.append(css);const js=document.createElement('script');js.src='/vendor/grapesjs/grapes.min.js';js.onload=()=>resolve();js.onerror=()=>{js.remove();reject(Error('The visual editor could not load. Please reload Workspace.'));};document.head.append(js);});return (window as any).grapesjs;}
export function splitSource(source:string){const doc=new DOMParser().parseFromString(source,'text/html');const scripts=[...doc.querySelectorAll('script')].map(n=>{const text=n.outerHTML;n.remove();return text}).join('');const templates=[...doc.querySelectorAll('template')].map(n=>{const text=n.outerHTML;n.remove();return text}).join('');const style=doc.head.querySelector('#workspace-overrides')?.textContent||'';doc.head.querySelector('#workspace-overrides')?.remove();return {doc,scripts,templates,style,body:doc.body.innerHTML};}
export function download(name:string,content:BlobPart,type='text/html'){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function exportSource(design:Design,html:string){const metadata={schema:1,id:design.id,baseId:design.base_id,revision:design.revision,assets:design.assets,assetOrigin:location.origin};return '<!-- FMI_WORKSPACE '+JSON.stringify(metadata)+' -->\n<!-- Edit HTML/CSS only. Preserve data-field, data-section, data-editor-text, element IDs, templates and scripts. Keep /assets/ URLs unchanged; use Workspace to replace media. Reimport into the same design. -->\n'+html.replaceAll('/assets/',location.origin+'/assets/');}
