import {createHash,createHmac,timingSafeEqual} from 'node:crypto';
export class HttpError extends Error {constructor(status,message){super(message);this.status=status;}}
export const templates=new Set(['rose-gold-blush-royal','royal-majesty','modern-minimal-royal','royal-prestige','royal-heritage','royal-grace','royal-crest','royal-legacy','emerald-noir','ivory-elegance','rose-gold-blush','modern-minimal','royal-elegance']);
const reserved=new Set(['grand-launch','api','assets','review','create','edit','dashboard','gallery','templates','login','signup','forgot-password','reset-password','checkout','about','contact','privacy-policy','terms-and-conditions','refund-policy','shipping-policy','affiliate','reviews','blog','robots.txt','sitemap.xml','demo','admin','www','manage','invite','terms','privacy','refund','shipping','akay']);
export function slugValue(value){if(typeof value!=='string'||!/^[a-z0-9](?:[a-z0-9-]{1,46}[a-z0-9])$/.test(value)||reserved.has(value))throw new HttpError(400,'Choose an available address of 3–48 lowercase letters, numbers or hyphens.');return value;}
export function tokenHash(token){if(typeof token!=='string'||!/^[a-f0-9]{64}$/.test(token))throw new HttpError(401,'A valid management key is required.');return createHash('sha256').update(token).digest('hex');}
export function verifyToken(token,hash){const actual=tokenHash(token);if(typeof hash!=='string'||hash.length!==64||!timingSafeEqual(Buffer.from(actual),Buffer.from(hash)))throw new HttpError(403,'This management key cannot access the invitation.');}
export function promotion(env=process.env,now=Date.now()){const startsAt=env.PROMOTION_START_AT||'2026-09-14T23:59:00+05:30';const endsAt=env.PROMOTION_END_AT||'2026-10-14T23:59:00+05:30';const start=Date.parse(startsAt),end=Date.parse(endsAt);if(!Number.isFinite(start)||!Number.isFinite(end)||end<=start)throw new HttpError(503,'Launch configuration is unavailable.');return {startsAt,endsAt,active:now>=start&&now<end};}
const strings={type:40,bride:100,groom:100,date:10,time:5,venue:200,address:600,welcome:2000,groomDetails:1000,brideDetails:1000,dressWomen:500,dressMen:500,transport:1500,accommodation:1500,gifts:1500};
const sectionKeys=['welcome','scratch','gallery','countdown','timeline','venue','dress','preEvents','transport','accommodation','gifts','rsvp'];
export function text(value,max,required=false){if(typeof value!=='string'||value.length>max||(required&&!value.trim())||/[\u0000-\u0008\u000b\u000c\u000e-\u001f]/.test(value))throw new HttpError(400,'One or more fields are missing or too long.');return value.trim();}
export function validateData(input,slug){if(!input||typeof input!=='object'||Array.isArray(input)||!templates.has(input.template))throw new HttpError(400,'Choose a supported template.');const data={id:slug,template:input.template};for(const [key,max]of Object.entries(strings))data[key]=text(input[key],max,['bride','groom','date','time'].includes(key));if(!/^\d{4}-\d{2}-\d{2}$/.test(data.date)||!/^([01]\d|2[0-3]):[0-5]\d$/.test(data.time))throw new HttpError(400,'Enter a valid event date and time.');const event=Date.parse(data.date+'T'+data.time+':00+05:30');if(!Number.isFinite(event)||new Date(data.date+'T00:00:00Z').toISOString().slice(0,10)!==data.date)throw new HttpError(400,'Enter a valid event date.');if(!['','/assets/track1.mp3','/assets/track3.mp3'].includes(input.music))throw new HttpError(400,'Choose an available music track.');data.music=input.music;if(!Array.isArray(input.photos)||input.photos.length>4)throw new HttpError(400,'Use up to four photos.');data.photos=input.photos.map(p=>{if(typeof p!=='string'||!(/^\/assets\/[a-zA-Z0-9_-]+\.(?:jpg|jpeg|png|webp)$/.test(p)||new RegExp('^/api/media\\?slug='+slug+'&slot=[0-3]$').test(p)))throw new HttpError(400,'Upload photos before saving.');return p;});data.sections={};for(const key of sectionKeys){if(typeof input.sections?.[key]!=='boolean')throw new HttpError(400,'Invalid section settings.');data.sections[key]=input.sections[key];}for(const key of ['timeline','preEvents']){if(!Array.isArray(input[key])||input[key].length>20)throw new HttpError(400,'Use up to 20 events per section.');data[key]=input[key].map(e=>{const time=text(e?.time,16,true);if(!/^\d{4}-\d{2}-\d{2}T([01]\d|2[0-3]):[0-5]\d$/.test(time)||!Number.isFinite(Date.parse(time)))throw new HttpError(400,'Invalid program time.');return {title:text(e.title,150,true),time,description:text(e.description,1000)};});}return {data,expires_at:new Date(event+30*86400000+3*3600000).toISOString()};}
export function validateRsvp(body){return {name:text(body.name,120,true),email:(()=>{const e=text(body.email,254,true);if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e))throw new HttpError(400,'Enter a valid email.');return e;})(),attendance:(()=>{if(!['yes','no'].includes(body.attendance))throw new HttpError(400,'Choose attendance.');return body.attendance;})(),guests:(()=>{const n=body.attendance==='no'?0:Number(body.guests??1);if(!Number.isInteger(n)||n<(body.attendance==='yes'?1:0)||n>100)throw new HttpError(400,'Invalid guest count.');return n;})(),message:text(body.message||'',2000)};}
export function configured(env=process.env){return Boolean(env.SUPABASE_URL&&env.SUPABASE_SERVICE_ROLE_KEY&&typeof env.RATE_LIMIT_SECRET==='string'&&env.RATE_LIMIT_SECRET.length>=32);}
export function clientRateKey(req,scope){const ip=req.headers['x-vercel-forwarded-for'];if(process.env.VERCEL&&!ip)throw new HttpError(503,'Request identity unavailable.');if(!process.env.RATE_LIMIT_SECRET||process.env.RATE_LIMIT_SECRET.length<32)throw new HttpError(503,'Service not configured.');return createHmac('sha256',process.env.RATE_LIMIT_SECRET).update(scope+':'+(typeof ip==='string'?ip.split(',')[0].trim():req.socket?.remoteAddress||'local')).digest('hex');}
export async function db(path,{method='GET',body,headers={}}={}){if(!configured())throw new HttpError(503,'Publishing is not configured yet.');const response=await fetch(process.env.SUPABASE_URL.replace(/\/$/,'')+'/rest/v1/'+path,{method,headers:{apikey:process.env.SUPABASE_SERVICE_ROLE_KEY,Authorization:'Bearer '+process.env.SUPABASE_SERVICE_ROLE_KEY,'Content-Type':'application/json',...headers},body:body===undefined?undefined:JSON.stringify(body)});if(!response.ok){if(response.status===409)throw new HttpError(409,'This address is already in use.');console.error('Database request failed',response.status);throw new HttpError(503,'Could not save your changes. Please try again.');}const raw=await response.text();return raw?JSON.parse(raw):null;}
export async function bodyJson(req,max=65536){if(Number(req.headers['content-length']||0)>max)throw new HttpError(413,'Request too large.');if(req.body!==undefined){let body;try{body=typeof req.body==='string'?JSON.parse(req.body):req.body;}catch{throw new HttpError(400,'Invalid JSON.');}if(!body||typeof body!=='object'||Array.isArray(body))throw new HttpError(400,'JSON object required.');if(Buffer.byteLength(JSON.stringify(body))>max)throw new HttpError(413,'Request too large.');return body;}let size=0,chunks=[];for await(const chunk of req){size+=chunk.length;if(size>max)throw new HttpError(413,'Request too large.');chunks.push(chunk);}try{const body=JSON.parse(Buffer.concat(chunks).toString());if(!body||typeof body!=='object'||Array.isArray(body))throw new Error();return body;}catch{throw new HttpError(400,'Invalid JSON.');}}
export function bearer(req){return String(req.headers.authorization||'').replace(/^Bearer /,'');}
export async function invitation(slug,token){const rows=await db('invitations?slug=eq.'+encodeURIComponent(slug)+'&select=*&limit=1');const row=rows[0];if(!row)throw new HttpError(404,'Invitation not found.');if(token!==undefined)verifyToken(token,row.management_hash);else if(!row.published||Date.parse(row.expires_at)<=Date.now())throw new HttpError(404,'Invitation is unavailable or expired.');return row;}
export async function rate(req,scope,limit,seconds){const result=await db('rpc/consume_rate_limit',{method:'POST',body:{p_key:clientRateKey(req,scope),p_limit:limit,p_seconds:seconds}});if(result!==true)throw new HttpError(429,'Too many requests. Please try again later.');}
export function respond(res,status,body){res.setHeader('Cache-Control','no-store');res.setHeader('X-Content-Type-Options','nosniff');res.status(status).json(body);}
export function fail(res,error){if(!(error instanceof HttpError))console.error('Request failed',error?.name);respond(res,error.status||500,{error:error instanceof HttpError?error.message:'Something went wrong. Please retry.'});}
export function method(req,allowed){if(!allowed.includes(req.method))throw new HttpError(405,'Method not allowed.');}



