-- Import as unpublished. Review media permissions before publication.
insert into public.template_catalog(id,name,description,collection,badge,sort_order,published) values
('rose-gold-blush-royal','Royal Imperial','Cinematic rose-gold opening with luxurious motion storytelling','royal','Cinematic',0,false),
('royal-majesty','Royal Majesty','Porcelain blue ballroom romance with painterly cinematic grandeur','royal','New',1,false),
('modern-minimal-royal','Royal Elegance','Velvet cream and crimson cinematic experience with palace motifs','royal','Premium',2,false),
('royal-prestige','Royal Prestige','Prestigious cinematic opening with refined elegance and grandeur','royal','New',3,false),
('royal-heritage','Royal Heritage','Timeless cinematic opening with regal heritage storytelling','royal','New',4,false),
('royal-heritage-1','Royal Heritage 1','Timeless cinematic opening with regal heritage storytelling','royal','New',21,false),
('royal-heritage-2','Royal Heritage 2','Timeless cinematic opening with regal heritage storytelling','royal','New',22,false),
('royal-heritage-3','Royal Heritage 3','Timeless cinematic opening with regal heritage storytelling','royal','New',23,false),
('royal-grace','Royal Grace','Sage garden serenity with pearl drapes and graceful cinematic reveal','royal','New',5,false),
('royal-crest','Royal Crest','Warm ivory florals, antique burgundy wax seal, and lakeside cinematic romance','royal','New',6,false),
('royal-legacy','Royal Legacy','Burgundy velvet curtains, antique gold ornament, and a timeless cinematic reveal','royal','New',7,false),
('emerald-noir','Emerald Noir','Deep green and gold with ornate corner accents and luxury door opening','classic','',8,false),
('luxury-pink','Luxury Pink','Deep green and gold with ornate corner accents and luxury door opening','classic','New',14,true),
('ivory-elegance','Crimson Royale','Dark charcoal base with gold and deep red accents, luxury card reveal','classic','',9,false),
('rose-gold-blush','Rose Gold Blush','Blush pink and rose gold with ornate floral door animation','classic','',10,false),
('modern-minimal','Modern Minimal','Deep navy and gold with geometric patterns and book-style opening','classic','New',11,false),
('royal-elegance','Majestic Love','Classic ivory and gold with palace motifs and velvet curtain reveal','classic','New',12,false)
('royal-heritage-4','Royal Heritage 4','Timeless cinematic opening with regal heritage storytelling','royal','New',24,false),
('royal-heritage-5','Blue & Pink Palace','Timeless cinematic opening with regal heritage storytelling','royal','New',25,false),
('royal-heritage-6','Pink Farm','Timeless cinematic opening with regal heritage storytelling','royal','New',26,false),
('royal-heritage-7','Traditional Anime South','Timeless cinematic opening with regal heritage storytelling','royal','New',27,false),
('royal-heritage-8','Sita Kalyanam','Timeless cinematic opening with regal heritage storytelling','royal','New',28,true),
('royal-heritage-9','Velicha Poove','Timeless cinematic opening with regal heritage storytelling','royal','New',29,true),
('royal-heritage-12','Kaatrukulle','Timeless cinematic opening with regal heritage storytelling','royal','New',32,false),
('royal-heritage-13','Kayil Midhakkum Kaatra nee','Timeless cinematic opening with regal heritage storytelling','royal','New',33,false),
('royal-heritage-14','Kadhal Lights','Timeless cinematic opening with regal heritage storytelling','royal','New',34,false),
('royal-prestige-1','Kavidhaye Theriyuma','Prestigious cinematic opening with refined elegance and grandeur','royal','New',21,false),
('royal-prestige-2','Rosu Rosu Rosu','Prestigious cinematic opening with refined elegance and grandeur','royal','New',22,true),
('royal-prestige-3','SAVE THE DATE test','Prestigious cinematic opening with refined elegance and grandeur','royal','New',23,false),
('royal-prestige-4','Gold Dream','Prestigious cinematic opening with refined elegance and grandeur','royal','New',24,true),
('royal-prestige-5','Ponmaalai','Prestigious cinematic opening with refined elegance and grandeur','royal','New',25,true),
('royal-prestige-6','Pookale Satru Oyvedungal','Prestigious cinematic opening with refined elegance and grandeur','royal','New',26,true),
('royal-prestige-7','White Forest','Prestigious cinematic opening with refined elegance and grandeur','royal','New',27,true),
('royal-prestige-8','Melliname','Prestigious cinematic opening with refined elegance and grandeur','royal','New',28,true),
('royal-prestige-9','ArmyMan & Wife','Prestigious cinematic opening with refined elegance and grandeur','royal','New',29,true),
('royal-prestige-10','StudioGen','Prestigious cinematic opening with refined elegance and grandeur','royal','New',30,true),
on conflict(id) do nothing;
