import {lazy,Suspense,useEffect,useState} from 'react';
import Home from './Home';
import Gallery from './Gallery';
import Invitation,{defaultInvite,readInvites,saveInvite} from './Invitation';
import type {InviteData} from './Invitation';
import {Header,Footer,Button} from './components';
import {templates} from './data';
import './editor.css';
import {publishDraft} from './guest-api';
import {PublicInvitation,GuestManagement,GuestDashboard} from './GuestPages';
import ContentPages from './ContentPages';
import ManagedPhoto from './ManagedPhoto';
const GrandLaunch=lazy(()=>import('./GrandLaunch'));
const AkayAdmin=lazy(()=>import('./AkayAdmin'));
const labelFor=(key:string)=>key.replace(/([A-Z])/g,' $1').replace(/^./,s=>s.toUpperCase());
function readPhoto(file:File){return new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>typeof r.result==='string'?resolve(r.result):reject(new Error('Photo could not be read.'));r.onerror=()=>reject(new Error('Photo could not be read. Please choose it again.'));r.onabort=()=>reject(new Error('Photo reading was interrupted.'));r.readAsDataURL(file);});}
export function Editor({initialData,onCloudSave}:{initialData?:InviteData;onCloudSave?:(data:InviteData)=>Promise<void>}){
const q=new URLSearchParams(location.search);const [data,setData]=useState<InviteData>(()=>{const saved=initialData||readInvites().find(i=>i.id===q.get('id'));return saved?{...defaultInvite,...saved,sections:{...defaultInvite.sections,...saved.sections}}:{...structuredClone(defaultInvite),id:crypto.randomUUID(),template:templates.some(t=>t.id===q.get('template'))?q.get('template')!:defaultInvite.template,type:q.get('type')||'wedding',music:['rose-gold-blush','emerald-noir'].includes(q.get('template')||'')?'/assets/track1.mp3':'/assets/track3.mp3'}});
const [error,setError]=useState(''),[reading,setReading]=useState(false),[saving,setSaving]=useState(false),[slug,setSlug]=useState(''),[notice,setNotice]=useState('');const set=<K extends keyof InviteData>(key:K,value:InviteData[K])=>setData(d=>({...d,[key]:value}));
const update=(key:'timeline'|'preEvents',index:number,field:'title'|'time'|'description',value:string)=>setData(d=>({...d,[key]:d[key].map((event,n)=>n===index?{...event,[field]:value}:event)}));
return <><Header/><main className="editor-shell"><h1>{q.get('id')?'Edit Your Invitation':'Create Your Invitation'}</h1><p className="muted">No signup needed. Save a draft on this device, or publish a guest invitation and keep its private recovery link.</p><form className="fmi-form" onSubmit={async e=>{e.preventDefault();setError('');setNotice('');setSaving(true);const action=(e.nativeEvent as SubmitEvent).submitter?.getAttribute('value');try{if(onCloudSave){await onCloudSave(data);setNotice('Your online invitation has been updated.');}else if(action==='publish'){if(!/^[a-z0-9][a-z0-9-]{2,47}$/.test(slug)){throw new Error('Choose a link with 3–48 lowercase letters, numbers or hyphens.');}saveInvite(data);const access=await publishDraft(data,slug);location.href='/manage/'+access.slug;}else{saveInvite(data);location.href='/invite/'+encodeURIComponent(data.id)}}catch(err){setError(err instanceof Error?err.message:'Could not save. Your changes are still here.')}finally{setSaving(false)}}}>
<label>Design<select value={data.template} onChange={e=>set('template',e.target.value)}>{templates.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>Background music<select value={data.music} onChange={e=>set('music',e.target.value)}><option value="">No music</option><option value="/assets/track1.mp3">Beautiful Dream</option><option value="/assets/track3.mp3">Chill</option>{data.music&&!['/assets/track1.mp3','/assets/track3.mp3'].includes(data.music)&&<option value={data.music}>Saved music</option>}</select></label><div className="editor-grid">{(['groom','bride','date','time','venue','address'] as const).map(key=><label key={key}>{labelFor(key)}<input required type={key==='date'?'date':key==='time'?'time':'text'} value={data[key]} onChange={e=>set(key,e.target.value)}/></label>)}</div>
{(['welcome','groomDetails','brideDetails','dressWomen','dressMen','transport','accommodation','gifts'] as const).map(key=><label key={key}>{labelFor(key)}<textarea rows={3} value={data[key]} onChange={e=>set(key,e.target.value)}/></label>)}
{(['timeline','preEvents'] as const).map(key=><fieldset className="event-editor" key={key}><legend>{key==='timeline'?'Program Timeline':'Pre-event Celebrations'}</legend><p className="muted">Events appear in the order shown. Dates and times use India Standard Time (IST).</p>{data[key].map((event,index)=><div className="event-editor-row" key={index}><div className="event-editor-heading"><h3>{key==='timeline'?'Program event':'Celebration'} {index+1}</h3><button type="button" className="editor-text-button" aria-label={`Remove ${key==='timeline'?'program event':'celebration'} ${index+1}`} onClick={()=>set(key,data[key].filter((_,n)=>n!==index))}>Remove</button></div><div className="editor-grid"><label>Title<input required value={event.title} onChange={e=>update(key,index,'title',e.target.value)}/></label><label>Date and time<input required type="datetime-local" value={event.time} onChange={e=>update(key,index,'time',e.target.value)}/></label></div><label>Description<textarea rows={2} value={event.description} onChange={e=>update(key,index,'description',e.target.value)}/></label></div>)}<button className="fmi-button outline" type="button" onClick={()=>set(key,[...data[key],{title:'',time:data.date+'T'+data.time,description:''}])}>+ Add {key==='timeline'?'program event':'celebration'}</button></fieldset>)}
<fieldset><legend>Visible sections</legend><div className="section-toggles">{Object.entries(data.sections).map(([key,on])=><label key={key}><input type="checkbox" checked={on} onChange={e=>set('sections',{...data.sections,[key]:e.target.checked})}/>{labelFor(key)}</label>)}</div></fieldset>
<label>Personal photos (up to 4, max 1 MB each)<input type="file" accept="image/jpeg,image/png,image/webp" multiple disabled={reading} onChange={async e=>{const input=e.currentTarget,files=Array.from(input.files||[]);if(!files.length)return;setError('');if(files.length>4||files.some(f=>f.size>1000000||!['image/jpeg','image/png','image/webp'].includes(f.type))){setError('Choose up to 4 image files, each smaller than 1 MB.');input.value='';return;}setReading(true);try{set('photos',await Promise.all(files.map(readPhoto)))}catch(err){setError(err instanceof Error?err.message:'Could not read the selected photos.')}finally{setReading(false);input.value='';}}}/></label><div className="editor-photos">{data.photos.map((src,index)=><figure key={index}><ManagedPhoto src={src} alt={`Invitation photo ${index+1}`}/><button type="button" onClick={()=>set('photos',data.photos.filter((_,n)=>n!==index))} aria-label={`Remove photo ${index+1}`}>Remove</button></figure>)}</div>
{!onCloudSave&&<label>Your public invitation link<span className="muted">findmyinvite.com/</span><input placeholder="ashoksupriya" maxLength={48} value={slug} onChange={e=>setSlug(e.target.value.toLowerCase().replace(/[^a-z0-9-]/g,''))}/><small>Choose 3–48 characters. Availability is checked when publishing. Anyone with this public link can view your invitation.</small></label>}{notice&&<p role="status">{notice}</p>}{reading&&<p role="status">Reading photos…</p>}{error&&<p className="editor-error" role="alert">{error}</p>}<div className="editor-actions"><button className="fmi-button" type="submit" disabled={reading||saving}>{saving?'Saving…':reading?'Reading photos…':onCloudSave?'Save Online Changes':'Save Local Draft & Preview'}</button>{!onCloudSave&&<button className="fmi-button" type="submit" value="publish" disabled={reading||saving}>{saving?'Publishing…':'Publish Free Launch Invitation'}</button>}<Button href="/dashboard" outline>My Invitations</Button></div></form></main><Footer/></>;
}
type GuestResponse={name:string;attendance:string;message:string;invitationId:string;guests?:string|number;email?:string};
function readResponses():{items:GuestResponse[];error:string}{try{const raw=JSON.parse(localStorage.getItem('findmyinvite-messages')||'[]');if(!Array.isArray(raw))throw new Error();return {items:raw.filter((m):m is GuestResponse=>m!==null&&typeof m==='object'&&typeof m.invitationId==='string'&&typeof m.name==='string'&&typeof m.attendance==='string').map(m=>({...m,email:typeof m.email==='string'?m.email:undefined,guests:typeof m.guests==='number'||typeof m.guests==='string'?m.guests:undefined})),error:''}}catch{return {items:[],error:'Guest responses could not be read from browser storage. Your stored data has not been changed.'}}}
function Dashboard(){const [items,setItems]=useState(readInvites),[responses,setResponses]=useState(readResponses),[error,setError]=useState(''),[deleted,setDeleted]=useState<InviteData|null>(null);useEffect(()=>{const refresh=()=>{setItems(readInvites());setResponses(readResponses())};window.addEventListener('focus',refresh);window.addEventListener('storage',refresh);return()=>{window.removeEventListener('focus',refresh);window.removeEventListener('storage',refresh)}},[]);
return <><Header/><main className="editor-shell"><h1>My Invitations</h1><GuestDashboard/><h2>Local drafts</h2><p className="muted">These drafts are saved on this device. Edit a draft and publish it to get a guest link that works on other devices.</p><Button href="/templates">Create Invitation</Button>{(error||responses.error)&&<p className="editor-error" role="alert">{error||responses.error}</p>}{deleted&&<p className="editor-undo" role="status">Invitation deleted. <button type="button" onClick={()=>{try{saveInvite(deleted);setItems(readInvites());setDeleted(null);setError('')}catch{setError('Could not restore this invitation. Browser storage may be full or unavailable.')}}}>Undo</button></p>}{items.length===0&&<p className="py-12">Your invitations will appear here.</p>}{items.map(i=>{const messages=responses.items.filter(m=>m.invitationId===i.id);return <article className="dashboard-card" key={i.id}><h2>{i.groom} & {i.bride}</h2><p>{i.date} · {i.venue}</p><div className="editor-actions dashboard-actions"><Button href={'/invite/'+encodeURIComponent(i.id)}>Preview</Button><Button href={'/create?id='+encodeURIComponent(i.id)} outline>Edit</Button><button className="editor-text-button" type="button" onClick={()=>{try{const raw=JSON.parse(localStorage.getItem('findmyinvite-invitations')||'[]');if(!Array.isArray(raw))throw new Error('Invalid saved data');const next=raw.filter(x=>!x||x.id!==i.id);localStorage.setItem('findmyinvite-invitations',JSON.stringify(next));setItems(readInvites());setDeleted(i);setError('')}catch{setError('Could not delete the invitation. Please check browser storage access.')}}}>Delete</button></div><details><summary>Guest responses ({messages.length})</summary>{messages.length===0?<p className="muted">No responses yet. Submit an RSVP from the saved invitation’s preview to try it.</p>:messages.map((m,n)=><div className="guest-response" key={n}><strong>{m.name}</strong><p>{m.attendance==='yes'?'Attending':m.attendance==='no'?'Not attending':m.attendance}{m.attendance==='yes'&&m.guests?` · ${m.guests} guest(s)`:''}</p>{m.email&&<p>{m.email}</p>}{typeof m.message==='string'&&m.message&&<p>{m.message}</p>}</div>)}</details></article>})}</main><Footer/></>;
}
function Other(){return <><Header/><main className="editor-shell"><h1>Page not found</h1><Button href="/">Return home</Button></main><Footer/></>}
export default function App(){const path=location.pathname;useEffect(()=>{if(path.startsWith('/invite/')||path.startsWith('/grand-launch')||path==='/akay'||path==='/akay/')return;const titles:Record<string,string>={'/':'Create Invitation Webpage Online for All Events','/templates':'Invitation Templates','/create':'Personalize Your Invitation','/dashboard':'My Invitations'};document.title=(titles[path]||path.slice(1).replaceAll('-',' '))+' | FindMyInvite';},[path]);return (path==='/akay'||path==='/akay/')?<Suspense fallback={<div className="akay-gate"/>}><AkayAdmin/></Suspense>:(path==='/grand-launch'||path==='/grand-launch/')?<Suspense fallback={<div style={{minHeight:'100svh',background:'#031c17'}}/>}><GrandLaunch/></Suspense>:path==='/'?<Home/>:path==='/templates'?<Gallery/>:path.startsWith('/invite/')?<Invitation/>:path==='/create'?<Editor/>:['/dashboard','/login','/signup','/forgot-password'].includes(path)?<Dashboard/>:path.startsWith('/manage/')?<GuestManagement slug={path.split('/')[2]} Editor={Editor}/>:['/about','/contact','/terms','/privacy-policy','/refund-policy','/shipping-policy','/blog'].includes(path)||path.startsWith('/blog/')?<ContentPages/>:/^\/[a-z0-9][a-z0-9-]{2,47}$/.test(path)?<PublicInvitation slug={path.slice(1)}/>:<Other/>}



