import {useEffect,useState} from 'react';
import {Header,Footer} from './components';
import './launch.css';
type Post={slug:string;title:string;excerpt:string;publishedAt:string;body:string};
const sections:Record<string,{title:string;paragraphs:string[]}>={
 '/about':{title:'About FindMyInvite',paragraphs:['FindMyInvite helps you create a digital invitation with animated designs, event details, photos and guest RSVP. Hosts sign in with email and password to save drafts and publish. Guests open the public invitation link with no account.','Choose a Classic or Royal design, personalize your details, and share the public invitation link. Open My Templates after you sign in to return to your invitations.']},
 '/contact':{title:'Contact',paragraphs:['Support contact details are awaiting configuration. Please do not send event details or private management links to an unverified address.']},
 '/privacy-policy':{title:'Privacy notice — launch draft',paragraphs:['Invitation details can include names, event times, venue addresses, photos and messages. Public invitation links are intended for sharing: anyone who receives one may view and forward it. Do not include information you do not want guests to see.','Guest RSVP submissions include the name, attendance choice, guest count and any message or email provided in the form. Hosts access responses after signing in, from My Templates.','Hosts create an email and password account to save a draft or publish. Guests open the public invitation link with no account. Password reset is not available yet. Browser storage may retain local drafts and older recovery links on your device.','The production architecture uses Vercel for hosting and uploaded media, and Supabase for invitation records, RSVP records, and host accounts. Local demo drafts may still remain only in the browser until published.','Anonymous usage events (page path, time on page, viewport size, and a random session identifier) are stored so the operator can review storefront traffic. They do not include names, RSVP content, passwords, or management keys. The operator page is not linked from public pages.','The business contact, retention periods and privacy request process must be confirmed before public launch. This draft does not claim a completed deletion process or a guaranteed retention period.']},
 '/terms':{title:'Terms — launch draft',paragraphs:['Only publish event details and media you have permission to share. Do not impersonate others or use invitations for spam, unlawful material or misleading messages.','Hosts manage invitations after signing in. Older invitations may still use a private recovery link; anyone holding that link can manage the invitation. Share only the public invitation link with guests.','Free creation is scheduled from 14 September 2026 at 11:59 PM IST to 14 October 2026 at 11:59 PM IST. The offer does not create a subscription or authorize a later charge. Regular listed prices remain ₹1,199 for Classic and ₹1,499 for Royal.','Business identity, support contact and final service terms are awaiting confirmation. No paid checkout is offered in this guest launch version.']},
 '/refund-policy':{title:'Payments and refunds',paragraphs:['The guest launch version does not collect payment details or process paid checkout. Invitations created under the free launch offer do not incur a purchase charge.','No subscription or automatic billing begins when the offer expires. Any future paid purchase must show its price and refund terms before you confirm payment.']},
 '/shipping-policy':{title:'Digital delivery',paragraphs:['FindMyInvite provides digital invitation webpages. No physical product is shipped.','After successful publishing, use the public invitation link to share with guests. Sign in and open My Templates to edit your invitation and review responses. A local preview is not a published invitation.']}
};
function isPost(p:unknown):p is Post{if(!p||typeof p!=='object')return false;const v=p as Record<string,unknown>;return ['slug','title','excerpt','body'].every(k=>typeof v[k]==='string')&&typeof v.publishedAt==='string'&&/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(String(v.slug))}
export default function ContentPages({path=location.pathname}:{path?:string}){const blog=path==='/blog'||path.startsWith('/blog/');const slug=path.startsWith('/blog/')?path.slice(6):'';const [posts,setPosts]=useState<Post[]>([]);const [state,setState]=useState<'loading'|'ready'|'error'>('loading');useEffect(()=>{if(!blog)return;setState('loading');const controller=new AbortController();fetch('/api/content?kind=blog'+(slug?'&slug='+encodeURIComponent(slug):''),{signal:controller.signal}).then(r=>{if(!r.ok)throw new Error();return r.json()}).then(data=>{setPosts((slug?[data.post]:Array.isArray(data.posts)?data.posts:[]).filter(isPost));setState('ready')}).catch(e=>{if(e.name!=='AbortError')setState('error')});return()=>controller.abort()},[blog,slug]);const page=sections[path];return <><Header/><main className="content-page">{blog?<><h1>{slug&&posts[0]?posts[0].title:'The FindMyInvite journal'}</h1>{state==='loading'?<p role="status">Loading articles…</p>:state==='error'?<p role="status">The journal is temporarily unavailable. Please try again later.</p>:!posts.length?<p>{slug?'This article is not available.':'No articles have been published yet. Check back for invitation ideas and product updates.'}</p>:slug?<article><time>{formatDate(posts[0].publishedAt)}</time>{posts[0].body.split(/\n\s*\n/).filter(Boolean).map((paragraph,i)=><p style={{whiteSpace:'pre-line'}} key={i}>{paragraph}</p>)}<a href="/blog">Back to the journal</a></article>:<div className="blog-list">{posts.map(post=><article key={post.slug}><time>{formatDate(post.publishedAt)}</time><h2><a href={'/blog/'+encodeURIComponent(post.slug)}>{post.title}</a></h2><p>{post.excerpt}</p></article>)}</div>}</>:page?<><h1>{page.title}</h1>{['/privacy-policy','/terms','/contact'].includes(path)&&<p className="policy-status">Launch preparation: business and support details are awaiting confirmation.</p>}{page.paragraphs.map(p=><p key={p}>{p}</p>)}</>:<><h1>Page not found</h1><p><a href="/">Return to FindMyInvite</a></p></>}</main><Footer/></>}
function formatDate(value:string){const date=new Date(value);return Number.isNaN(date.getTime())?'':new Intl.DateTimeFormat('en-IN',{dateStyle:'long'}).format(date)}
