export const occasions = [['wedding','Wedding Invitation'],['engagement','Engagement Invitation'],['wedding-reception','Wedding & Reception Invitation'],['reception','Reception only invitation'],['birthday','Birthday Invitation'],['opening-ceremony','Opening Ceremony Invitation'],['anniversary','Anniversary Invitation'],['housewarming','Housewarming Invitations'],['party','Party Invitations'],['baby-shower','Baby shower'],['custom','Custom invitation']];
export type GalleryTier='premium'|'elite'|'free';
export const galleryTiers:GalleryTier[]=['premium','elite','free'];
export const galleryTierLabels:Record<GalleryTier,string>={premium:'Premium',elite:'Elite',free:'Free'};
export const galleryTierBlurb:Record<GalleryTier,string>={
 premium:'Flagship cinematic invitations with the richest motion openings.',
 elite:'Elevated Royal designs with distinctive ceremony atmospheres.',
 free:'Elegant animated Classic invitations for every occasion.'
};
const premiumIds=new Set(['royal-heritage-8','royal-heritage-9','royal-prestige-2','royal-prestige-4','royal-prestige-5','royal-prestige-6','royal-prestige-7','royal-prestige-8','royal-prestige-9','royal-prestige-10','royal-prestige-11']);
const retiredPremiumIds=new Set(['rose-gold-blush-royal','royal-majesty','modern-minimal-royal','royal-prestige','royal-heritage','royal-crest','royal-heritage-1','royal-heritage-2','royal-heritage-3','royal-heritage-4','royal-heritage-5','royal-heritage-6','royal-heritage-7','royal-heritage-12','royal-heritage-13','royal-heritage-14','royal-prestige-1','royal-prestige-3']);
export function galleryTierFor(id:string,royal=false):GalleryTier{
 if(retiredPremiumIds.has(id))return 'premium';
 if(premiumIds.has(id))return 'premium';
 if(royal)return 'elite';
 return 'free';
}
export function isPublicGalleryTemplate(id:string){
 return !retiredPremiumIds.has(id);
}
export function normalizeGalleryCollection(value:string|null|undefined):GalleryTier{
 if(value==='elite'||value==='free'||value==='premium')return value;
 if(value==='classic')return 'free';
 if(value==='royal')return 'premium';
 return 'premium';
}
export const templates = [
{id:'royal-sanctuary',name:'Royal Sanctuary',description:'A sacred temple opening, golden sanctuary gates and a celebration framed in ivory and gold',image:'royal-sanctuary/0746f651bbbdcaf6.jpg',video:'',badge:'New',royal:true,tier:'elite' as GalleryTier,color:'#fdf6e2'},
{id:'royal-heritage-wedding',name:'Royal Heritage Wedding',description:'Regal arches, glowing lamps and golden frames for a timeless celebration',image:'royal-heritage-wedding/364e5ed899368f4d.webp',video:'',badge:'New',royal:true,tier:'elite' as GalleryTier,color:'#2a1408'},
 {id:'royal-temple',name:'Royal Temple',description:'A grand temple celebration with floating clouds, ringing bells and rich gold details',image:'temple/bg3.webp',video:'',badge:'New',royal:true,tier:'elite' as GalleryTier,color:'#bd985b'},
 {id:'rose-gold-blush-royal',name:'Royal Imperial',description:'Cinematic rose-gold opening with luxurious motion storytelling',image:'50122aee9f7395c4.jpg',video:'0cfccffffc862729.mp4',heroVideo:'rose-gold-blush-royal-hero.mp4',badge:'Cinematic',royal:true,tier:'premium' as GalleryTier,color:'#8b2337'},
 {id:'royal-majesty',name:'Royal Majesty',description:'Porcelain blue ballroom romance with painterly cinematic grandeur',image:'5a3bf145f59aa9c7.jpg',video:'royal-majesty.mp4',badge:'New',royal:true,tier:'premium' as GalleryTier,color:'#536e83'},
 {id:'modern-minimal-royal',name:'Royal Elegance',description:'Velvet cream and crimson cinematic experience with palace motifs',image:'15b12cdf24c3ee92.jpg',video:'royal-elegance-royal.mp4',badge:'Premium',royal:true,tier:'premium' as GalleryTier,color:'#6c1826'},
 {id:'royal-prestige',name:'Royal Prestige',description:'Prestigious cinematic opening with refined elegance and grandeur',image:'9b73577a4b10e8db.jpg',video:'c7238b2b655c3014.mp4',badge:'New',royal:true,tier:'premium' as GalleryTier,color:'#8b2337'},
 {id:'royal-prestige-1',name:'Kavidhaye Theriyuma',description:'Prestigious cinematic opening with refined elegance and grandeur',image:'royal-prestige-1.jpg',video:'royal-prestige-1.mp4',heroVideo:'royal-prestige-1-hero.mp4',music:'vazhithunaiye.mp3',musicName:'Vazhithunaiye',badge:'New',royal:true,tier:'premium' as GalleryTier,color:'#A16948'},
 {id:'royal-prestige-2',name:'Rosu Rosu Rosu',description:'Prestigious cinematic opening with refined elegance and grandeur',image:'royal-prestige-2.jpg',video:'royal-prestige-2.mp4',heroVideo:'royal-prestige-2-hero.mp4',music:'vazhithunaiye.mp3',musicName:'Vazhithunaiye',badge:'New',royal:true,tier:'premium' as GalleryTier,color:'#957A41'},
 {id:'royal-prestige-3',name:'SAVE THE DATE test',description:'Prestigious cinematic opening with refined elegance and grandeur',image:'royal-prestige-3.jpg',video:'royal-prestige-3.mp4',heroVideo:'royal-prestige-3-hero.mp4',music:'vazhithunaiye.mp3',musicName:'Vazhithunaiye',badge:'New',royal:true,tier:'premium' as GalleryTier,color:'#957A41'},
 {id:'royal-prestige-4',name:'Gold Dream',description:'Prestigious cinematic opening with refined elegance and grandeur',image:'royal-prestige-4.jpg',video:'royal-prestige-4.mp4',heroVideo:'royal-prestige-4-hero.mp4',music:'vazhithunaiye.mp3',musicName:'Vazhithunaiye',badge:'New',royal:true,tier:'premium' as GalleryTier,color:'#8F4003'},
 {id:'royal-prestige-5',name:'Ponmaalai',description:'Prestigious cinematic opening with refined elegance and grandeur',image:'royal-prestige-5.jpg',video:'royal-prestige-5.mp4',heroVideo:'royal-prestige-5-hero.mp4',music:'vazhithunaiye.mp3',musicName:'Vazhithunaiye',badge:'New',royal:true,tier:'premium' as GalleryTier,color:'#A26B48'},
 {id:'royal-prestige-6',name:'Pookale Satru Oyvedungal',description:'Prestigious cinematic opening with refined elegance and grandeur',image:'royal-prestige-6.jpg',video:'royal-prestige-6.mp4',heroVideo:'royal-prestige-6-hero.mp4',music:'vazhithunaiye.mp3',musicName:'Vazhithunaiye',badge:'New',royal:true,tier:'premium' as GalleryTier,color:'#BC8F2F'},
 {id:'royal-prestige-7',name:'White Forest',description:'Prestigious cinematic opening with refined elegance and grandeur',image:'royal-prestige-7.jpg',video:'royal-prestige-7.mp4',heroVideo:'royal-prestige-7-hero.mp4',music:'vazhithunaiye.mp3',musicName:'Vazhithunaiye',badge:'New',royal:true,tier:'premium' as GalleryTier,color:'#475527'},
 {id:'royal-prestige-8',name:'Melliname',description:'Prestigious cinematic opening with refined elegance and grandeur',image:'royal-prestige-8.jpg',video:'royal-prestige-8.mp4',heroVideo:'royal-prestige-8-hero.mp4',music:'vazhithunaiye.mp3',musicName:'Vazhithunaiye',badge:'New',royal:true,tier:'premium' as GalleryTier,color:'#7E6F56'},
 {id:'royal-prestige-9',name:'ArmyMan & Wife',description:'Prestigious cinematic opening with refined elegance and grandeur',image:'royal-prestige-9.jpg',video:'royal-prestige-9.mp4',heroVideo:'royal-prestige-9-hero.mp4',music:'vazhithunaiye.mp3',musicName:'Vazhithunaiye',badge:'New',royal:true,tier:'premium' as GalleryTier,color:'#8D6C52'},
 {id:'royal-prestige-10',name:'StudioGen',description:'Prestigious cinematic opening with refined elegance and grandeur',image:'royal-prestige-10.jpg',video:'royal-prestige-10.mp4',heroVideo:'royal-prestige-10-hero.mp4',music:'vazhithunaiye.mp3',musicName:'Vazhithunaiye',badge:'New',royal:true,tier:'premium' as GalleryTier,color:'#8A125E'},
 {id:'royal-prestige-11',name:'Tamil Ponnu Daww',description:'Prestigious cinematic opening with refined elegance and grandeur',image:'royal-prestige-11.jpg',video:'royal-prestige-11.mp4',heroVideo:'royal-prestige-11-hero.mp4',music:'vazhithunaiye.mp3',musicName:'Vazhithunaiye',badge:'New',royal:true,tier:'premium' as GalleryTier,color:'#D4911E'},
 {id:'royal-heritage',name:'Royal Heritage',description:'Timeless cinematic opening with regal heritage storytelling',image:'3c934c61dec8899c.jpg',video:'royal-heritage.mp4',badge:'New',royal:true,tier:'premium' as GalleryTier,color:'#884936'},
 {id:'royal-heritage-1',name:'Royal Heritage 1',description:'Timeless cinematic opening with regal heritage storytelling',image:'royal-heritage-1.jpg',video:'royal-heritage-1.mp4',badge:'New',royal:true,tier:'premium' as GalleryTier,color:'#884936'},
 {id:'royal-heritage-2',name:'Royal Heritage 2',description:'Timeless cinematic opening with regal heritage storytelling',image:'royal-heritage-2.jpg',video:'royal-heritage-2.mp4',badge:'New',royal:true,tier:'premium' as GalleryTier,color:'#884936'},
 {id:'royal-heritage-3',name:'Royal Heritage 3',description:'Timeless cinematic opening with regal heritage storytelling',image:'royal-heritage-3.jpg',video:'royal-heritage-3.mp4',badge:'New',royal:true,tier:'premium' as GalleryTier,color:'#884936'},
 {id:'royal-heritage-4',name:'Royal Heritage 4',description:'Timeless cinematic opening with regal heritage storytelling',image:'royal-heritage-4.jpg',video:'royal-heritage-4.mp4',badge:'New',royal:true,tier:'premium' as GalleryTier,color:'#884936'},
 {id:'royal-heritage-5',name:'Blue & Pink Palace',description:'Timeless cinematic opening with regal heritage storytelling',image:'royal-heritage-5.jpg',video:'royal-heritage-5.mp4',heroVideo:'royal-heritage-5-hero.mp4',badge:'New',royal:true,tier:'premium' as GalleryTier,color:'#884936'},
 {id:'royal-heritage-6',name:'Pink Farm',description:'Timeless cinematic opening with regal heritage storytelling',image:'royal-heritage-6.jpg',video:'royal-heritage-6.mp4',heroVideo:'royal-heritage-6-hero.mp4',badge:'New',royal:true,tier:'premium' as GalleryTier,color:'#884936'},
 {id:'royal-heritage-7',name:'Traditional Anime South',description:'Timeless cinematic opening with regal heritage storytelling',image:'royal-heritage-7.jpg',video:'royal-heritage-7.mp4',heroVideo:'royal-heritage-7-hero.mp4',badge:'New',royal:true,tier:'premium' as GalleryTier,color:'#884936'},
 {id:'royal-heritage-8',name:'Sita Kalyanam',description:'Timeless cinematic opening with regal heritage storytelling',image:'royal-heritage-8.jpg',video:'royal-heritage-8.mp4',heroVideo:'royal-heritage-8-hero.mp4',music:'royal-heritage-8-music.mp3',badge:'New',royal:true,tier:'premium' as GalleryTier,color:'#6E1A28'},
 {id:'royal-heritage-9',name:'Velicha Poove',description:'Timeless cinematic opening with regal heritage storytelling',image:'royal-heritage-9.jpg',video:'royal-heritage-9.mp4',heroVideo:'royal-heritage-9-hero.mp4',music:'royal-heritage-9-music.mp3',badge:'New',royal:true,tier:'premium' as GalleryTier,color:'#9B2158'},
 // reserved: royal-heritage-10 (Spiderverse, draft PR #24), royal-heritage-11 (KTM couple White, draft PR #25) — held off the allocator until those land or close.
 {id:'royal-heritage-12',name:'Kaatrukulle',description:'Timeless cinematic opening with regal heritage storytelling',image:'royal-heritage-12.jpg',video:'royal-heritage-12.mp4',heroVideo:'royal-heritage-12-hero.mp4',music:'vazhithunaiye.mp3',musicName:'Vazhithunaiye',badge:'New',royal:true,tier:'premium' as GalleryTier,color:'#9B2158'},
 {id:'royal-heritage-13',name:'Kayil Midhakkum Kaatra nee',description:'Timeless cinematic opening with regal heritage storytelling',image:'royal-heritage-13.jpg',video:'royal-heritage-13.mp4',heroVideo:'royal-heritage-13-hero.mp4',music:'vazhithunaiye.mp3',musicName:'Vazhithunaiye',badge:'New',royal:true,tier:'premium' as GalleryTier,color:'#A16948'},
 {id:'royal-heritage-14',name:'Kadhal Lights',description:'Timeless cinematic opening with regal heritage storytelling',image:'royal-heritage-14.jpg',video:'royal-heritage-14.mp4',heroVideo:'royal-heritage-14-hero.mp4',music:'vazhithunaiye.mp3',musicName:'Vazhithunaiye',badge:'New',royal:true,tier:'premium' as GalleryTier,color:'#A16948'},
 {id:'royal-grace',name:'Royal Grace',description:'Sage garden serenity with pearl drapes and graceful cinematic reveal',image:'eaaba0b5d7aeba99.jpg',video:'royal-grace.mp4',badge:'New',royal:true,tier:'elite' as GalleryTier,color:'#59634b'},
 {id:'royal-crest',name:'Royal Crest',description:'Warm ivory florals, antique burgundy wax seal, and lakeside cinematic romance',image:'15cbf1df9056e121.jpg',video:'royal-crest.mp4',badge:'New',royal:true,tier:'premium' as GalleryTier,color:'#713647'},
 {id:'royal-legacy',name:'Royal Legacy',description:'Burgundy velvet curtains, antique gold ornament, and a timeless cinematic reveal',image:'58bf76a6b043df9f.jpg',video:'royal-legacy.mp4',badge:'New',royal:true,tier:'elite' as GalleryTier,color:'#581d2c'},
 {id:'emerald-noir',name:'Emerald Noir',description:'Deep green and gold with ornate corner accents and luxury door opening',image:'4cfcddd6f8996fe3.png',video:'',badge:'Limited Edition',royal:false,tier:'free' as GalleryTier,color:'#123d32'},
 {id:'luxury-pink',name:'Luxury Pink',description:'Cream card with dusty rose florals, muted gold and romantic serif names',image:'4cfcddd6f8996fe3.png',video:'',badge:'New',royal:false,tier:'free' as GalleryTier,color:'#b05e77'},
 {id:'ivory-elegance',name:'Crimson Royale',description:'Dark charcoal base with gold and deep red accents, luxury card reveal',image:'',video:'',badge:'Most Liked',royal:false,tier:'free' as GalleryTier,color:'#451d26'},
 {id:'rose-gold-blush',name:'Rose Gold Blush',description:'Blush pink and rose gold with ornate floral door animation',image:'',video:'',badge:'',royal:false,tier:'free' as GalleryTier,color:'#a86675'},
 {id:'modern-minimal',name:'Modern Minimal',description:'Deep navy and gold with geometric patterns and book-style opening',image:'',video:'',badge:'New',royal:false,tier:'free' as GalleryTier,color:'#182d46'},
 {id:'royal-elegance',name:'Majestic Love',description:'Classic ivory and gold with palace motifs and velvet curtain reveal',image:'',video:'',badge:'New',royal:false,tier:'free' as GalleryTier,color:'#a88643'},
];
export function catalogMusicUrl(template:{id:string;royal?:boolean;music?:string}){
 if(template.music)return template.music.startsWith('/')?template.music:'/assets/'+template.music;
 return template.royal||template.id==='ivory-elegance'?'/assets/track3.mp3':'/assets/track1.mp3';
}
export function catalogMusicName(template:{musicName?:string;name?:string}){
 return String(template.musicName||'').trim()||'';
}
export const features=[['infinity','Share to Unlimited Guests','One link, infinite reach — no per-guest charges, ever.'],['pen','Unlimited Edits Until the Event Date','Refine every detail right up to your big day.'],['hand','Scratch to Reveal Date','Interactive scratch card reveals the event date with a delightful surprise.'],['timer','Live Countdown','Animated countdown timer to your special day.'],['inbox','Guest Messaging & Inbox','Receive messages, attendance confirmations & guest counts.'],['music','Background Music','Romantic instrumentals with elegant mute toggle.'],['map','Venue with Maps','Embedded Google Maps for seamless directions.'],['wand','Premium Animations','3D door reveals, curtains, sparkles & more.'],['image','Custom Image Upload','Upload slideshow photos & hero background images.'],['brush','Full Customization','Toggle sections, dress codes, events & more.']];
export const classicBenefits=['Access to FindMyInvite Classic Invitations','5 Premium Animated Templates','1 Invitation Webpage','Unlimited Edits Until Event Date','Buy More Invitations Anytime (Add-On)','Guest Messaging & Inbox','Music, Photos & Custom Uploads','Google Maps & Multi-Language Support','Analytics & Page View Tracking','Automatic Privacy Protection After the Event'];
export const royalBenefits=['Access to ALL Classic + Royal Invitations','13 Premium Animated Templates','Cinematic Royal Invitation Experience','Luxury Video-Based Opening Experience','3D Door & Curtain Reveal Animations','Cinematic Hero Backgrounds','Premium Motion Storytelling','Exclusive Royal Template Collection','“Save the Date” — one-tap add to Google, Apple, Outlook & Yahoo calendars'];
export const faqs=[['How does the digital invitation work?','After purchase, fill in your event details through a simple form. We generate a unique link for your personalized invitation webpage that you can share with guests via WhatsApp, email, or any messaging platform.'],['Can I edit my invitation after creating it?','Yes! You can edit your invitation details anytime for unlimited times until the event date & time from your dashboard. Changes are reflected instantly on the live invitation page.'],['How many invitations can I create?','The base plan allows you to create 1 invitation webpage. To create more invitations, purchase additional credits or an add-on plan.'],['Is there a limit on how many guests can view my invitation?','No! Your invitation link can be viewed by unlimited guests with no additional charges.'],['What payment methods are accepted?','UPI, credit cards, debit cards, net banking, and wallets. This frontend preview does not process payments.'],['Can I get a refund?','All purchases are final. Refunds may only be considered for duplicate or erroneous payments. See our Refund Policy for details.']];
export const reviews=[['MOHAMED NISAR',"With heartfelt gratitude, I want to congratulate you and your entire team for the wonderful work you've done on my invitation. You've not only made my special day more meaningful, but you make every occasion special and memorable for everyone who uses your service. I may not know much about you or your team personally, but I truly appreciate the effort, creativity, and dedication behind your work. I'd be happy to learn more about your team and the other services you offer, and I'll gladly recommend you to my friends. I wish you and your team continued success your professionalism and timely responses will surely take your venture to new heights."],['Mohit Srivastava',"The service you offer is just phenomenal I've never seen a card this elegant and beautifull. So thank you for everything 🙏 💓"],['Rabia Waseem','Just created the card and showed it to my brother, he absolutely loved it. Thank you for your brilliant customer support, you should definitely have more designs and options'],['Tasneem Barde','Such a beautiful and well-designed wedding webpage! Everything was easy to find and perfectly organized. 🫶🏻'],['Rabia Waseem','Absolutely loved it, you should definitely have more designs and options']];

