import {useEffect, useState} from 'react';
export const LAUNCH_START='2026-09-14T23:59:00+05:30';
export const LAUNCH_END='2026-10-14T23:59:00+05:30';
let configurationRequest:Promise<any>|undefined;
function getConfiguration(){return configurationRequest??=fetch('/api/invitations?action=config').then(r=>{if(!r.ok)throw new Error();return r.json()})}
export function useLaunchPromotion(){
 const [schedule,setSchedule]=useState({startsAt:LAUNCH_START,endsAt:LAUNCH_END,offset:0,verified:false});
 const [now,setNow]=useState(Date.now());
 useEffect(()=>{let disposed=false;getConfiguration().then(data=>{if(disposed)return;const p=data.promotion;if(p)p.serverNow=p.serverNow||data.serverNow;if(data.configured!==true||!p||![p.startsAt,p.endsAt,p.serverNow].every(v=>typeof v==='string'&&Number.isFinite(Date.parse(v)))||Date.parse(p.endsAt)<=Date.parse(p.startsAt))return;setSchedule({startsAt:p.startsAt,endsAt:p.endsAt,offset:Date.parse(p.serverNow)-Date.now(),verified:true})}).catch(()=>{});const timer=setInterval(()=>setNow(Date.now()),1000);return()=>{disposed=true;clearInterval(timer)}},[]);
 const time=now+schedule.offset;const starts=Date.parse(schedule.startsAt),ends=Date.parse(schedule.endsAt);
 return {...schedule,phase:time<starts?'planned':time<ends?'active':'ended',remaining:Math.max(0,(time<starts?starts:ends)-time)};
}
export const launchFeatures=[['pen','Edit Your Details','Personalize your names, venue, program and celebrations.'],['hand','Scratch to Reveal Date','An interactive scratch card reveals your event date.'],['timer','Event Countdown','A countdown to your special day.'],['inbox','Guest RSVP','Collect attendance and messages from your guests.'],['music','Background Music','Choose an available instrumental or keep your invitation silent.'],['map','Venue Directions','Share your venue and a link to directions.'],['wand','Animated Openings','Choose Classic animations or Royal cinematic previews.'],['image','Personal Photos','Add photos to your invitation slideshow.']];
export const launchBenefits=['One personalized invitation webpage','Editable event details and sections','Guest RSVP and messages','Photo slideshow and available music','Calendar download and venue directions'];
export const launchFaqs=[['Do I need an account?','Yes, to save a draft or publish. Create an account with email and password. Guests still open your public invitation link without signing in. Password reset is not available yet.'],['When is creating an invitation free?','The launch offer is scheduled from 14 September 2026 at 11:59 PM IST until 14 October 2026 at 11:59 PM IST. Both Classic and Royal designs are included during this window.'],['Will I be charged automatically?','No. The launch offer does not start a subscription, collect a payment card, or automatically bill you later. Regular listed prices are ₹1,199 for Classic and ₹1,499 for Royal.'],['Where are my invitations?','Sign in and open My Templates. Your drafts and published invitations are saved to that account.'],['Can I change my details?','Sign in, open My Templates, and manage the invitation. Preview the updated details before sharing your public link.']];
