import {get,put,del} from '@vercel/blob';
import {Readable} from 'node:stream';
import {pipeline} from 'node:stream/promises';
import {HttpError,slugValue,invitation,bearer,bodyJson,respond,fail,method,rate} from '../server/core.mjs';
export function decodePhoto(value){if(typeof value!=='string')throw new HttpError(400,'Choose an image.');const match=/^data:image\/(jpeg|png|webp);base64,([A-Za-z0-9+/]+={0,2})$/.exec(value);if(!match)throw new HttpError(400,'Use a JPEG, PNG or WebP image.');const bytes=Buffer.from(match[2],'base64');if(bytes.length<12||bytes.length>1048576)throw new HttpError(413,'Each photo must be no larger than 1 MB.');const actual=bytes[0]===255&&bytes[1]===216&&bytes[2]===255?'jpeg':bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10]))?'png':bytes.toString('ascii',0,4)==='RIFF'&&bytes.toString('ascii',8,12)==='WEBP'?'webp':null;if(actual!==match[1])throw new HttpError(400,'The image does not match its file type.');return {bytes,contentType:'image/'+actual};}
export default async function handler(req,res){try{method(req,['GET','POST','DELETE']);if(!process.env.BLOB_READ_WRITE_TOKEN)throw new HttpError(503,'Photo uploads are not configured yet.');const q=new URL(req.url,'https://findmyinvite.com').searchParams,slug=slugValue(q.get('slug')),slot=q.get('slot');if(!/^[0-7]$/.test(slot||''))throw new HttpError(400,'Invalid photo slot.');const token=req.headers.authorization?bearer(req):undefined;const row=await invitation(slug,req.method==='GET'?token:bearer(req));if(req.method==='GET'&&token===undefined&&!row.data.photos?.includes('/api/media?slug='+slug+'&slot='+slot))throw new HttpError(404,'Photo not found.');const pathname='invitations/'+row.id+'/'+slot;
 if(req.method==='POST'){await rate(req,'upload:'+slug,40,3600);const photo=decodePhoto((await bodyJson(req,1450000)).dataUrl);await put(pathname,photo.bytes,{access:'private',addRandomSuffix:false,allowOverwrite:true,contentType:photo.contentType,cacheControlMaxAge:60});return respond(res,200,{url:'/api/media?slug='+slug+'&slot='+slot});}
 if(req.method==='DELETE'){await del(pathname);return respond(res,200,{ok:true});}
 const blob=await get(pathname,{access:'private',useCache:false});if(!blob||blob.statusCode!==200)throw new HttpError(404,'Photo not found.');res.setHeader('Content-Type',blob.blob.contentType);res.setHeader('Cache-Control','private, no-store');res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Content-Disposition','inline');await pipeline(Readable.fromWeb(blob.stream),res);
 }catch(error){if(!res.headersSent)fail(res,error);else res.destroy();}}

